/**
 * History desk content bank. Each entry is ~300 words of original
 * ZooTown-written prose about Missoula's past. Wikipedia / archive links are
 * cited as references (the article body is ours, not theirs).
 *
 * The daily writer pulls these in order and stops when the bank is exhausted.
 * Admin can extend the bank or write new entries directly through the UI.
 */
import type { DraftArticle } from "./writer.js";

export const HISTORY_BANK: DraftArticle[] = [
  {
    headline: "The Hellgate Treaty of 1855",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Hellgate_treaty",
    body: `## A treaty signed in a tense valley\n\nIn July 1855, Territorial Governor Isaac Stevens met with leaders of the Salish, Pend d'Oreille, and Kootenai peoples at a cottonwood grove near the mouth of the Bitterroot Valley. The meeting, brokered with chronically poor translation, produced what came to be known as the Hellgate Treaty.\n\n## What the document said\n\nThe treaty consolidated the three tribes onto the Flathead Reservation north of Missoula and opened the rest of the valley to settlement. Chief Victor of the Bitterroot Salish refused to sign away his people's home in the Bitterroot itself, securing a clause that promised a survey to determine whether the Bitterroot or Jocko valley would become the permanent reservation. That survey never happened in good faith; in 1891 the U.S. Army forcibly removed the Bitterroot Salish to the Jocko, a march remembered as one of Montana's deepest injustices.\n\n## Why it still shapes Missoula\n\nThe treaty's footprint is everywhere in modern Missoula. Place names — Lolo, Frenchtown, Arlee, Ravalli — are Salish or trace back to figures involved in the treaty era. Land use disputes from water rights to highway easements still cite Hellgate. And the Confederated Salish and Kootenai Tribes remain a sovereign government whose territory borders the city, with growing cultural and economic influence on the region.\n\n## A note on language\n\nThe city's name is itself a treaty-era artifact: Missoula comes from the Salish term often rendered nemissoolatakoo, "place of frozen water," describing the narrow gap east of town where ambushes once made the canyon a feared crossing. The English version, Hellgate, comes from French trappers' translation of the Salish warning. Two languages, the same warning, the same gap.`,
  },
  {
    headline: "The Big Burn of 1910",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Great_Fire_of_1910",
    body: `## Two days that defined American firefighting\n\nOn August 20 and 21, 1910, a hurricane-force dry wind swept across the northern Rockies and turned thousands of smoldering fires into a single firestorm. Three million acres burned across Idaho and western Montana in roughly 48 hours. Eighty-seven people died, most of them young U.S. Forest Service firefighters and the immigrant laborers who fought alongside them.\n\n## Missoula at the center\n\nMissoula was the staging ground. The brand-new Forest Service, headquartered in the Northern Rockies Region from offices on East Broadway, sent crews into the Bitterroot, the Coeur d'Alene, and the St. Joe. Trains pulled into the Missoula yards carrying survivors, the burned, and the dead. A makeshift morgue opened downtown. The city's hospitals filled to capacity.\n\n## The legacy in policy\n\nThe Big Burn changed how the United States manages forests. Convinced that aggressive suppression could prevent another catastrophe, the Forest Service committed to fighting every fire on every acre — a policy that defined a century of land management and that researchers now believe contributed to today's bigger, hotter fires by allowing fuels to accumulate. The Smokejumpers, headquartered at Missoula's Aerial Fire Depot since 1954, trace their lineage straight to the lessons of 1910.\n\n## Where to see it\n\nThe Smokejumper Visitor Center off Highway 10 keeps photographs, gear, and oral histories from the 1910 fires and the decades of crews that followed. Granite Pass north of Lolo and the burn scars visible from the Lolo Trail still bear the geometry of that fire more than a century later — strips of even-aged lodgepole pine in country that would otherwise look very different.`,
  },
  {
    headline: "How the Northern Pacific Railroad Reshaped Missoula",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Northern_Pacific_Railway",
    body: `## A town becomes a hub\n\nMissoula existed before the Northern Pacific arrived in 1883, but the town that exists today was largely drawn by the railroad. The NP chose the Missoula valley as a division point — a place where crews changed, locomotives were serviced, and freight was reorganized for the climb over Mullan Pass to the east and the long descent into Idaho to the west.\n\n## The Northside takes shape\n\nThe yards, roundhouse, and shops went in north of the Clark Fork. Worker housing followed: the Northside neighborhood's grid of small frame houses dates almost entirely to the railroad's first two decades in town. Many of the residents were Italian, Irish, and Scandinavian immigrants drawn by steady wages. Their churches, social halls, and cemeteries — St. Mary's Cemetery, the old Polish Hall, the Sons of Norway lodge — give the Northside a cultural depth most visitors never see from the highway.\n\n## What the railroad moved\n\nLumber, livestock, copper from Butte, and people. Missoula was the gateway to the Bitterroot apple boom, and refrigerated railcars sent western Montana fruit to Minneapolis and Chicago. The Anaconda Company's copper traveled east through Missoula on its way to East Coast refineries. The University of Montana's growth in the early 1900s depended on students and faculty arriving by train.\n\n## What's left today\n\nThe Northern Pacific Depot at the north end of Higgins still stands as a restaurant and event space — an Italianate Revival reminder of how central the railroad once was. BNSF, the NP's modern descendant, still runs freight through town, and the whistle at the Higgins crossing remains one of Missoula's most familiar nighttime sounds.`,
  },
  {
    headline: "Fort Missoula and the Buffalo Soldiers' Bicycle Corps",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/25th_Infantry_Regiment_Bicycle_Corps",
    body: `## A fort built for a long-vanished mission\n\nThe U.S. Army established Fort Missoula in 1877 to keep an eye on the recently displaced Salish and to provide a base for operations during the Nez Perce War. By the 1890s its original purpose had faded, and the post took on stranger and more interesting roles than its founders ever imagined.\n\n## A bicycle as a war machine\n\nIn 1896 the 25th Infantry Regiment, an all-Black unit under white officers, was stationed at Fort Missoula. Lieutenant James Moss convinced the Army to test whether bicycles could replace horses for long-distance reconnaissance. The Bicycle Corps rode 800 miles to Yellowstone and back over rough mountain roads — and then, in 1897, made a 1,900-mile journey from Missoula to St. Louis on single-speed bikes weighing about thirty pounds, carrying their own gear and rations.\n\nThey averaged better than fifty miles a day across the Great Plains in July. The experiment proved the concept and was promptly forgotten by an Army that preferred horses. The soldiers themselves, members of one of the famed Buffalo Soldier regiments, returned to a country that gave them little credit.\n\n## The fort's later lives\n\nDuring World War II, Fort Missoula became an internment site for Italian merchant seamen seized in U.S. ports and for several hundred Japanese-American men taken from the West Coast. Many of the Japanese-American detainees were later transferred to camps farther inland; some Italian internees stayed in Missoula and became part of the community after the war.\n\nThe Historical Museum at Fort Missoula now occupies the old post and tells these layered stories — military, civil rights, immigration, and labor — in the same buildings where they happened.`,
  },
  {
    headline: "Higgins Avenue and the Bridge That Made the City",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Higgins_Avenue_Bridge",
    body: `## A bridge before there was much of a town\n\nCaptain Christopher Higgins and his partner Francis Worden ran the trading post that became Missoula. By the 1870s they understood that the future of the settlement depended on linking the south side of the Clark Fork — where the Hellgate trail ran — to the north bank, where the railroad would eventually arrive. The first Higgins Avenue bridge, a wooden toll structure, opened in 1873.\n\n## Three bridges, one location\n\nFloods and decay required replacement; the current concrete arch bridge dates to 1962, with major rehabilitation in the 2000s. The location, however, has stayed the same for 150 years. That continuity is the reason Higgins is Missoula's main street — every successive bridge committed the city to growing along that axis.\n\n## A street with structure\n\nWalk Higgins today and the 19th-century footprint is still legible. The Florence Hotel block, the Wilma Theater, the Missoula Mercantile site (now Mercantile Hotel), the old First National Bank — these are bones of a downtown that was largely built between 1890 and 1925. Many storefronts retain their cast-iron columns and pressed-metal cornices.\n\n## A linear public space\n\nHiggins is also one of the few American downtown streets where you can stand on the bridge, look upstream, and see mountains in every direction. That accident of geography — a bridge framed by Mount Sentinel, Mount Jumbo, and Waterworks Hill — has done more for Missoula's identity than any planning document. River City Roots Festival, the farmers' market, Out to Lunch, the Brewers Festival, and the Christmas Stroll all use the same few blocks year after year, reinforcing the idea that this is the heart of town.`,
  },
  {
    headline: "The University of Montana's Founding",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/University_of_Montana",
    body: `## A campus on a floodplain\n\nThe University of Montana opened in 1895 in temporary quarters downtown, with a charter that made it the state's flagship liberal arts institution. By 1898 the first permanent buildings — Main Hall and Science Hall — were rising on a former orchard at the base of Mount Sentinel.\n\n## Main Hall and the M\n\nMain Hall's bell tower has been the school's symbol since the day it opened. The "M" on the side of Mount Sentinel followed in 1909, originally laid out in whitewashed stones by a forestry class. Generations of students have repainted it; the trail to the M is one of the most-walked footpaths in the state.\n\n## Forestry, journalism, and the long bench\n\nThe College of Forestry, founded in 1913, became one of the country's most respected schools of natural resource management. It produced foresters, ecologists, and writers — including Norman Maclean and a long line of people whose careers shaped the U.S. Forest Service. The School of Journalism, established in 1914, became another distinctive program, training reporters who staffed papers across the West.\n\n## Growth and trouble\n\nThe school grew steadily through the 20th century and quickly during the post-WWII GI Bill era. It absorbed Missoula's economy in important ways: the largest employer in the county, the producer of much of its cultural life, and the institution whose students gave the city its famously young median age.\n\nLike many flagships, UM has wrestled with enrollment declines and budget cuts since 2010. It has also kept its distinctive feel — a smaller campus than its peers, with a quieter rhythm and a fiercer attachment to place. The Oval, the M trail, and the bell from Main Hall remain landmarks not just for the campus but for the city.`,
  },
  {
    headline: "The 1910 Floods and the Building of the Levees",
    kind: "history",
    body: `## A river that built and broke the town\n\nMissoula sits at the confluence of the Clark Fork, the Bitterroot, and the Blackfoot. That geography made it a meeting place for thousands of years before settlement, and it has made the city flood-prone for as long as anyone has lived here. The biggest of those floods, in the spring of 1908 and again in 1910, redrew the riverbank and forced the city's first real engineering response.\n\n## What the 1908 flood did\n\nA combination of heavy snowpack, a warm late-May, and rapid melt sent the Clark Fork well over its banks. The old wooden Higgins bridge survived but barely; the Northern Pacific yards on the north side flooded for days; whole sections of the McCormick Park flats sat under water. Several houses on the Northside were lifted off their foundations and floated downstream.\n\n## The response\n\nFlood-control measures came in fits and starts. The Civilian Conservation Corps reshaped the lower Clark Fork banks in the 1930s. The state and federal governments built levees through the 1940s and 1950s, particularly around the rail yards and what is now McCormick Park. The Milltown Dam, downstream from the city, briefly moderated some peak flows — though it created a long-term sediment and contamination problem that took until its 2008 removal to begin solving.\n\n## What's left\n\nThe levees are why Missoula sits where it does today. They protect tens of millions of dollars of downtown property and allow the river to function as a recreational asset rather than a periodic threat. Brennan's Wave, the Caras Park amphitheater, and the Riverbank Trail all exist because the river is contained. Big floods will come again, and Missoula's flood plans now account for that explicitly.`,
  },
  {
    headline: "The Anaconda Company's Long Shadow",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Anaconda_Copper",
    body: `## A copper company that owned a state\n\nFor most of the 20th century, the Anaconda Copper Mining Company was the dominant economic force in Montana. Anaconda employed tens of thousands across mines, smelters, sawmills, and processing plants, and it owned most of the state's daily newspapers — including the Missoulian, until the chain was sold in 1959.\n\n## Missoula's role in the company's empire\n\nMissoula was not a mining town but a mill town. The Bonner Mill, downstream from the city on the Blackfoot, was the largest sawmill in Montana for much of the century and supplied lumber for Anaconda's mines and the railroads carrying its copper. Smaller mills ran in Frenchtown and at Champion. The wood economy ran on Anaconda's demand for timbers, ties, and construction lumber, and tens of thousands of workers depended on it.\n\n## The environmental cost\n\nUpstream from Missoula, the Clark Fork drains the Butte/Anaconda mining district. A century of unregulated mine waste left arsenic, lead, and copper contamination across the basin. The 2008 removal of Milltown Dam, immediately downstream from the city, was driven primarily by the need to deal with toxic sediment trapped behind it — one of the largest Superfund cleanups in the country.\n\n## What replaced it\n\nWhen Anaconda collapsed in the 1980s, Missoula lost mill jobs at Bonner, Frenchtown, and Champion in quick succession. The city's economy reoriented around the University, healthcare, government agencies, and a growing recreation and tourism sector. The transition was painful and is in some ways still underway: rural families that once worked at the mills did not always find equivalent jobs in town, and parts of the regional economy never fully recovered. But Missoula itself became more diversified, and arguably more resilient, than the Anaconda era allowed.`,
  },
  {
    headline: "The Mansfield Library and the Senator's Quiet Legacy",
    kind: "history",
    body: `## A library named after the longest-serving Senate majority leader\n\nMike Mansfield, a Butte miner turned UM history professor turned U.S. senator, represented Montana from 1953 to 1977 and served sixteen years as Senate majority leader — still the record. When the University of Montana built its central research library in 1979, it was named for him.\n\n## A reading room as civic infrastructure\n\nThe Mansfield Library is the largest research library in Montana, with more than a million volumes and a collection that includes the K. Ross Toole Archives of regional history. It is also the de facto public library of west-central Montana for serious researchers, with access agreements that let community members read materials they could not find anywhere else in the state.\n\n## Mansfield himself\n\nMansfield arrived at the University of Montana in 1933 with no high school diploma — he had left home as a teenager and worked the Butte mines — and earned bachelor's and master's degrees while teaching part-time. He served in Congress for thirty-four years, then spent another eleven as U.S. ambassador to Japan, where he is still remembered for his patient diplomatic style. He returned to Missoula in his final years and remained connected to the university until his death in 2001.\n\n## Why the library matters\n\nThe Mansfield Center, also named for him, runs ethics and public-policy programs that draw national speakers to campus. The library hosts visiting scholars, civic forums, and student research that often touches on Missoula's own history. Generations of Missoulians have used the building as a working office during finals week and a quiet refuge during the long winter. For a senator famous for refusing pomp, the building is a fitting monument — useful, unshowy, and full of light.`,
  },
  {
    headline: "Why Missoula Became a Center of Smokejumping",
    kind: "history",
    body: `## A job invented in the Northern Rockies\n\nSmokejumping — parachuting firefighters into remote terrain — was first tested by the U.S. Forest Service in 1939 at the Seeley Lake Ranger Station, an hour northeast of Missoula. The mountainous, road-less country of the Bob Marshall and the Selway-Bitterroot made traditional ground crews too slow; jumpers could reach a new fire within an hour rather than a day.\n\n## The Aerial Fire Depot\n\nIn 1954, the Forest Service consolidated its smokejumper training and dispatch at a purpose-built facility on Highway 10 west of Missoula. The Aerial Fire Depot was the largest of its kind in the country and remains the operational home of the Missoula Smokejumpers and the Forest Service's main parachute loft. Each year, jumpers from across the West gather there for training before fire season.\n\n## Mann Gulch\n\nThe profession's hardest lesson came on August 5, 1949, when thirteen smokejumpers died in Mann Gulch above the Gates of the Mountains, east of Helena. Foreman Wagner Dodge survived by lighting an escape fire — a now-standard technique that he invented on the spot. The dead included men whose families still live in western Montana. Norman Maclean, whose own father had been a Missoula minister, spent his last years writing Young Men and Fire, a meditation on Mann Gulch that became one of the defining books about wildfire.\n\n## The depot today\n\nThe Smokejumper Visitor Center is open every summer with tours of the loft and a small museum. Jumpers still scramble out of the same hangars to fires across the West. The job has changed — better aircraft, better gear, more sophisticated weather prediction — but the geography is the same, and Missoula remains the place where the trade was invented and where it is still taught.`,
  },
  {
    headline: "Caras Park, the Carousel, and the Reclaiming of the Riverfront",
    kind: "history",
    body: `## A parking lot becomes a park\n\nUntil the late 1980s, the south bank of the Clark Fork in downtown Missoula was a railroad yard, a parking lot, and a string of half-vacant industrial buildings. Caras Park, the open green space and amphitheater at the foot of Higgins, did not exist. The riverfront was something the city had turned its back on.\n\n## A community decision\n\nA series of master plans through the 1980s and 1990s, driven by Mayor Dan Kemmis, the Missoula Redevelopment Agency, and a remarkable amount of volunteer energy, gradually reclaimed the south bank. Brennan's Wave (added in 2006) gave kayakers a downtown play feature; the Riverfront Trail linked Caras to the McCormick Park ballfields and on to the University; the carousel anchored the park's east end starting in 1995.\n\n## A Carousel for Missoula\n\nA Carousel for Missoula is a fully hand-carved, locally built carousel — the first such carousel constructed in the United States in nearly sixty years when it opened. Chuck Kaparich, a local cabinetmaker, organized the project; hundreds of volunteers carved horses, painted scenery, and raised money. It remains one of the city's most distinctive civic objects — a working carousel, free or nearly free to ride, built by the people who live around it.\n\n## What it changed\n\nCaras Park is now the venue for Out to Lunch, River City Roots, the Saturday farmers' market, and most summer festivals. The riverbank is one of the most-used public spaces in the city. The change from rail yard to park happened in less than a generation, almost entirely through volunteer time and small public investments. Visitors who arrive in Missoula today often assume the riverfront was always like this; it was not.`,
  },
  {
    headline: "The 1980s and the Slow Death of the Bonner Mill",
    kind: "history",
    body: `## The biggest mill in the state\n\nThe Bonner Mill, on the Blackfoot River five miles east of Missoula, was for most of the 20th century the largest sawmill in Montana. At peak it employed more than a thousand workers and supplied lumber to the Anaconda Company's mines, to the railroads, and to construction markets across the West.\n\n## The downturn\n\nBy the 1980s, the timber industry across the Northwest was contracting. Old-growth supply on federal lands was tightening; the Anaconda Company collapsed in 1983; cheaper Canadian lumber undercut domestic mills; the spotted owl litigation later in the decade froze additional federal timber sales. Bonner did not close all at once — it changed hands multiple times, ran in shifts, and limped through the early 2000s before the final shutdown in 2008.\n\n## What it meant for Missoula\n\nThe closure of Bonner was the last act in a longer story. The Champion Mill in Frenchtown closed in 2010. Smaller mills around the valley closed earlier. Thousands of mill jobs disappeared from the regional economy over roughly two decades. Many of the affected workers commuted from rural communities — Lolo, Bonner, Frenchtown, Potomac — and the loss was felt unevenly across the area.\n\n## What replaced it\n\nMissoula's economy reoriented around healthcare (St. Patrick's and Community Medical Center became two of the largest employers), the University, Forest Service and other federal agencies, software and outdoor-industry companies, and a growing tourism and recreation sector. The Bonner site itself, after years of remediation, is now an industrial park with a brewery, distilleries, and a riverside event venue. The change is visible: where there were once mountains of sawdust, there are now hop fields and pickleball courts. The transition is incomplete, and the cultural memory of the mills runs deep east of town.`,
  },
  {
    headline: "Hellgate Canyon and the Naming of the City",
    kind: "history",
    body: `## A gap with a fearsome name\n\nEast of downtown Missoula, the Clark Fork River cuts a narrow canyon between Mount Sentinel and Mount Jumbo. The Salish called the spot "place of frozen water" or, in earlier translations, "place of ambush" — the canyon was a chokepoint where war parties from the plains could surprise the valley's residents.\n\nFrench-Canadian trappers in the early 1800s heard the Salish warnings, and translated the name as Porte de l'Enfer — Gate of Hell. English speakers shortened it to Hellgate. The first non-Native settlement in the area, Hellgate Trading Post, sat just below the canyon's mouth.\n\n## A town and its names\n\nFor about a decade in the mid-19th century, the settlement was simply Hellgate. When Christopher Higgins and Francis Worden moved their trading operation upstream to the better-watered site that became modern downtown, they renamed it Missoula Mills — and eventually just Missoula — using a more euphonious version of the Salish name for the same canyon.\n\nSo the city carries two names for the same place: Missoula, the soft Salish form, and Hellgate, the French translation of the Salish warning. Hellgate High School, Hellgate Canyon, and the Hellgate Treaty all use the older, harder name; the city itself uses the gentler one.\n\n## What you can still see\n\nThe canyon is still narrow and still windy. Interstate 90 and the Milwaukee Road rail line both pass through it; the Kim Williams Trail runs the south wall as a footpath. The wind that funnels through Hellgate in winter is what makes downtown Missoula colder than the surrounding country, and it is also why Mount Sentinel's south face stays mostly snow-free even in February. A Salish ambush point is now a daily commute.`,
  },
  {
    headline: "The Wilma Theater and the Vaudeville Era",
    kind: "history",
    body: `## A theater on the river\n\nThe Wilma Theater opened in 1921 at the corner of Higgins and the Clark Fork, built by Bill Simons, a Missoula entrepreneur with a flair for showmanship. Named for his wife Edna Wilma, the seven-story brick structure was the tallest building in Montana for several years and the most ornate theater between Spokane and Minneapolis.\n\n## Vaudeville, then movies, then everything else\n\nThe Wilma's original life was as a vaudeville house. Acts on the western circuit booked through Missoula on their way between Spokane and Salt Lake City. By the late 1920s, with vaudeville fading, the venue converted to a movie palace. A pipe organ, still intact, accompanied silent films. The theater hosted political conventions, school graduations, weddings, and political speeches — the building was a civic space as much as an entertainment one.\n\n## The 1970s and after\n\nLike many downtown theaters in the era of suburban multiplexes, the Wilma struggled through the 1970s and 1980s. It was nearly demolished more than once. A succession of owners and a determined preservation effort kept the doors open. Today the Wilma operates as a concert venue with a busy schedule of touring musicians and comics; it is one of the most acoustically distinctive rooms in the Rocky Mountain West, and a place where Missoula audiences have heard everyone from Willie Nelson to Wilco to Joan Baez.\n\n## Inside the building\n\nThe seven stories above the theater contain apartments, offices, and a basement bar that traces back to the 1920s. The marquee at Higgins and Front, a 1930s addition, is one of the most photographed objects in downtown Missoula. The building's longevity says something about the city: nearly every American town once had a Wilma; Missoula still has its.`,
  },
  {
    headline: "The Milltown Dam Removal",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Milltown_Dam",
    body: `## A century-old dam comes down\n\nIn 2008, after more than a decade of planning and a Superfund process that took years to negotiate, the Milltown Dam at the confluence of the Clark Fork and Blackfoot rivers was removed. It was, at the time, the largest dam removal in U.S. history and one of the largest river restoration projects ever undertaken.\n\n## Why it was built — and why it had to come out\n\nThe original Milltown Dam was completed in 1908 to power a sawmill and later the Anaconda smelter's operations. Over a century, a century of mining waste from Butte and Anaconda had settled into the reservoir behind it — millions of cubic yards of arsenic-, lead-, and copper-laden sediment, the largest concentrated repository of mine waste in the West. A 1996 ice jam threatened to breach the dam and release that toxic load downstream into Missoula's drinking water.\n\nThe federal Superfund process forced the issue. The dam was decommissioned, the contaminated sediment dug out and trucked to a permanent containment site, and the rivers were allowed to re-meander through a restored confluence.\n\n## The result\n\nThe rivers reconnected for the first time in a century. Bull trout, native cutthroats, and other migratory species began moving back upstream. Caras Wildlife Refuge and Sha-Ron Park, both built into the restored confluence, are now among the most heavily used outdoor spaces in the valley. The water quality in the lower Clark Fork has improved measurably.\n\n## What it taught\n\nMilltown became a national reference case for industrial-era river restoration. The project's combination of dam removal, sediment cleanup, and habitat reconstruction influenced similar work on the Elwha in Washington and the Klamath on the Oregon-California border. Five miles east of downtown Missoula, the rivers run free.`,
  },
  {
    headline: "Lolo Trail and the Nez Perce Crossing",
    kind: "history",
    body: `## A path older than the United States\n\nThe Lolo Trail crosses the Bitterroot Mountains southwest of Missoula, linking the Bitterroot Valley to the Clearwater River country of Idaho. Indigenous peoples — Nez Perce, Salish, and others — used it for at least several thousand years to move between summer hunting grounds on the eastern plains and winter villages on the western rivers.\n\n## Lewis and Clark, 1805 and 1806\n\nThe Lewis and Clark expedition crossed the Lolo in September 1805 and again in June 1806. The 1805 crossing nearly destroyed them — early snow, near-starvation, and the necessity of slaughtering horses to eat. The Nez Perce who fed and resupplied them in Idaho almost certainly saved the expedition. The 1806 crossing on the return trip was easier; the men were in better shape and traveled with Nez Perce guides.\n\n## 1877: the Nez Perce War\n\nA generation later, the Lolo Trail became the path of one of the most consequential events in Northern Rockies history. In 1877, Chief Joseph's band and several allied groups, refusing to be forced onto a reservation, crossed the Lolo from Idaho into Montana on their way toward Canada. They were pursued by the U.S. Army across more than 1,000 miles. The Battle of the Big Hole, fought in the Bitterroot Valley south of Missoula, was one of the war's worst days for both sides.\n\nThe Nez Perce were eventually intercepted in the Bear Paw Mountains, forty miles from Canada. Chief Joseph's surrender speech — "I will fight no more forever" — has been quoted ever since.\n\n## The trail today\n\nU.S. Highway 12 follows much of the historical route. The Lolo Pass Visitor Center marks the summit and houses interpretive exhibits about the Indigenous, exploration, and military histories of the trail. Most of the surrounding country is now National Forest, accessible to hikers and pack-trippers.`,
  },
  {
    headline: "The Garden City Nickname",
    kind: "history",
    body: `## A claim with some history behind it\n\nMissoula began calling itself "The Garden City" sometime in the 1880s. The label survives on water towers, taproom names, and city signage, and it traces back to a real agricultural moment in the city's history.\n\n## Bitterroot apples and irrigation\n\nThrough the late 19th and early 20th centuries, the Bitterroot and Missoula valleys became significant fruit-growing regions. McIntosh, Wealthy, and Wagener apples shipped east from packing houses around Florence, Stevensville, and Hamilton. Cherry, plum, and pear orchards lined the south end of Missoula. The Big Ditch irrigation project, completed in 1907, watered roughly 25,000 acres of the Bitterroot Valley and converted dry bench land into orchards almost overnight.\n\nThe Garden City label was a marketing slogan as much as a description — a way for the railroad and the early Chamber of Commerce to attract settlers and investors. It worked. Whole subdivisions of Missoula in the 1900s and 1910s were marketed to fruit-growing aspirants.\n\n## The boom went bust\n\nThe Bitterroot apple boom collapsed by the 1920s. A combination of pests, a couple of brutal winters, the rise of Washington's Wenatchee Valley as a larger apple producer, and the difficulty of long-distance shipping ended the commercial fruit economy. Many of the speculative orchards were abandoned within a decade of being planted.\n\n## What remains\n\nIndividual orchards still survive — a few commercial operations, plenty of backyard trees, the Missoula Community Orchard at the north end of town, the Western Cider operation that uses regional apples. The Garden City nickname kept going long after the orchards left. It now refers more to Missoula's reputation for tree-lined streets, dense gardens, and a community deeply attached to its public green spaces than to any particular apple. Visitors who arrive in summer often understand why.`,
  },
  {
    headline: "How Missoula Became a Refugee Resettlement City",
    kind: "history",
    body: `## A surprising role for a small western city\n\nMissoula has resettled refugees from many of the conflicts of the post-Cold War era. The city's role as a designated U.S. resettlement site began in the 1970s with Vietnamese and Hmong arrivals; it accelerated in the 1990s with families from Bosnia and Eritrea; and it expanded again starting in 2016 with arrivals from Syria, Iraq, the Democratic Republic of the Congo, and Afghanistan.\n\n## How it works\n\nResettlement is handled by Soft Landing Missoula, a nonprofit working with the International Rescue Committee and the federal Department of State. Arriving families are housed, helped with paperwork and language services, connected with employers and schools, and supported through the difficult first year. The model relies heavily on volunteer hosts and local partnerships.\n\n## A national debate, a local response\n\nIn 2016 the Missoula resettlement program briefly became a flashpoint in a national political debate over refugee admissions. Public meetings drew hundreds of supporters and a smaller number of vocal opponents. The City Council and Mayor John Engen issued public statements affirming the program; the resettlement work continued.\n\n## What's visible today\n\nMissoula's refugee community is small in absolute numbers — a few hundred families across the program's history — but their presence has reshaped parts of the city. The grocery shelves at Albertsons and Orange Street Food Farm now stock injera, halal meats, Bosnian coffee, and Syrian olives. Hellgate High School and Big Sky High School are more linguistically diverse than they were a generation ago. Refugee-owned restaurants and businesses dot the strip malls along Brooks and Reserve. For a small city far from the coasts, Missoula is unusually connected to the rest of the world, and most of that connection runs through families who chose to live here when they could have lived anywhere they were allowed.`,
  },
  {
    headline: "The Pattee Canyon and the Forest at the City's Edge",
    kind: "history",
    body: `## A neighborhood inside a forest\n\nPattee Canyon, on the southeast edge of Missoula, is one of the only American neighborhoods where you can step out of a residential street and into a working national forest. The Pattee Canyon Recreation Area, managed by the Lolo National Forest, sits at the top of the canyon and is one of the most heavily used trail systems in western Montana.\n\n## Logging, then recreation\n\nThe canyon was logged heavily in the early 20th century to supply Missoula's mills and the Anaconda Company's mines. By the 1930s, with the easiest timber cut and the Forest Service taking a more conservation-oriented approach, the canyon shifted toward recreation. The Civilian Conservation Corps built the first formal trails and the picnic area still in use today.\n\n## A trail system that anchors a neighborhood\n\nPattee Canyon contains roughly thirty miles of formal trails plus a dense web of unofficial connectors. Cross-country skiers groom several loops each winter; mountain bikers use the lower trails year-round; trail runners use the system as their training ground. The Lolo National Forest's proximity is why Missoula consistently ranks high in surveys of cities with easy outdoor access. A serious trail-runner can leave a downtown office at noon, run a four-mile loop in Pattee, and be back at a desk by 1:30.\n\n## Fire and the future\n\nThe canyon's dense conifer stands make it a real wildfire risk. Fuel reduction work, prescribed burns, and brush clearing have been ongoing for two decades, partly to protect the neighborhood that has grown up around the forest. Climate change has lengthened fire seasons; recent summers have closed parts of Pattee for weeks at a time. The forest at the city's edge is part of what makes Missoula distinctive — and part of what the city will have to actively protect to keep.`,
  },
  {
    headline: "Missoula's Brewing Tradition",
    kind: "history",
    body: `## A beer town with old roots\n\nMissoula's brewing scene is among the densest per capita in the United States, but it is not a recent invention. The Garden City Brewery operated downtown from 1881 to Prohibition. The Highlander Brewing Company brewed in town from 1933 (immediately after Repeal) until 1964. For roughly eighty years there was always at least one commercial brewery in Missoula, and for much of that period there were several.\n\n## A long dry spell, then a revival\n\nFrom 1964 to 1995, Missoula had no commercial brewery. The change came in 1995 when Bayern Brewing, founded by Bavarian-trained brewer Jürgen Knöller, opened in a former rail building on the north side. Bayern was followed by Big Sky Brewing in 1995 (now in a purpose-built facility off Hwy 93), Kettlehouse in 1996, Tamarack in 2007, Draught Works in 2011, Imagine Nation in 2014, and many more since.\n\n## A different kind of craft economy\n\nMontana's beer laws — a unique three-pint tap room cap and an 8 p.m. closing requirement for breweries without restaurants — have created a brewery culture distinct from Portland or Denver. Missoula's tap rooms are explicitly social spaces: short visits, lots of families, an early evening crowd. The taproom on Hickory Street at Kettlehouse and the riverfront patio at Imagine Nation have become casual community gathering places in a way that bars usually are not.\n\n## The festival\n\nThe Garden City Brewfest, held every May at Caras Park, brings together most of the Montana craft scene and has been an unofficial start of Missoula summer for two decades. Knöller's Bayern has been a fixture; so has the volunteer-driven Missoula Brewers' Association. For a city of seventy thousand people, the depth of brewing knowledge and the casual sophistication of the average drinker are both unusual — and both rooted in a tradition that runs back to 1881.`,
  },
  // --- NEW 30 HISTORY ENTRIES ---
  {
    headline: "The Rattlesnake Wilderness — A City's Backyard Goes Federal",
    kind: "history",
    sourceUrl: "https://www.fs.usda.gov/r01/lolo/recreation/rattlesnake-national-recreation-area-wilderness",
    body: `## A drainage that defines Missoula's north edge\n\nRattlesnake Creek drops out of the Rattlesnake Mountains and enters the Clark Fork just north of the Higgins Avenue bridge, marking the city's northern edge as cleanly as Mount Sentinel marks the east. The creek and its canyon have been the drinking water source for Missoula since the 1880s, and for most of that time the city managed the upper watershed as a protected catchment.\n\n## The 1983 Wilderness and NRA designation\n\nIn 1983, Congress passed the Rattlesnake National Recreation Area and Wilderness Act, formally protecting more than 33,000 acres of the upper Rattlesnake drainage as both a National Recreation Area — open to hiking, skiing, and camping — and a Wilderness Area, prohibiting mechanized use. The dual designation was a compromise between recreation interests and strict wilderness advocates; it has generally worked well, with heavy trail use in the lower recreation area giving way to quieter wilderness in the upper drainage.\n\n## A trail system inside the city limits\n\nThe lower Rattlesnake NRA begins less than a mile from downtown Missoula, accessible by foot from the Northside neighborhood. The main trail corridor follows the creek through mixed forest and meadow, with dozens of side trails branching to ridgelines and high lakes. The proximity is extraordinary: grizzly bears have been documented within three miles of the city center, and the drainage holds populations of wolverine, mountain goat, and bull trout.\n\n## Water and wilderness together\n\nThe Rattlesnake's dual identity — working watershed and recreational wilderness — makes it unique among urban adjacent protected areas in the United States. The water intakes are still in the lower canyon, still drawing from streams protected partly by the wilderness designation that surrounds them. Missoula drinks from a Wilderness Area, which is not a sentence that applies to many American cities.`,
  },
  {
    headline: "The Florence Hotel — Built Three Times, Burned Twice",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Florence_Hotel_(Missoula,_Montana)",
    body: `## A landmark that refused to stay down\n\nThe Florence Hotel has stood at 111 North Higgins Avenue since 1941, but the site has held a hotel since 1888 — and the current building is the third attempt to keep one there. The original Florence, built for railway travelers and early settlers, burned in 1913. Its replacement, a 106-room hostelry that became a regional gathering place, burned in 1936. The current building rose in 1941, during the Depression, through a community financing effort led by Missoula businessman Walter McLeod.\n\n## An Art Moderne jewel\n\nSpokane architect G.A. Pehrson designed the current Florence in Art Moderne style — a sleek, seven-story terra cotta and rose-colored structure with curved corners, glass shower doors, underground parking (among the first in the Northwest), and the region's first central air conditioning. John Wayne reportedly slept there during a filming trip to Montana. The building was listed on the National Register of Historic Places in 1992.\n\n## Reinvention and preservation\n\nThe Florence remained a hotel through the 1970s, when it was converted to offices and retail. In subsequent decades it cycled through uses while remaining a visual anchor for the north end of Higgins. A major renovation in the 2010s and early 2020s converted it to mixed-use residential and commercial space while preserving its historic exterior and public lobby.\n\n## What it means on Higgins\n\nThe Florence is one of three buildings at the intersection of Higgins and Front — alongside the Wilma Theater and the old Missoula Mercantile — that define downtown's historic character. The fact that it burned twice and came back both times, and that the third version has now lasted eighty years, says something about how seriously Missoula has taken its built history. The terra cotta facade on a winter morning, pink in the early light, is one of the city's best views.`,
  },
  {
    headline: "The Bitterroot Valley's Apple Boom — and Bust",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Bitterroot_Valley",
    body: `## A valley sold on apples\n\nBetween roughly 1900 and 1920, promoters, railroads, and irrigation companies convinced thousands of settlers that the Bitterroot Valley south of Missoula was the next great apple-growing region of America. They were not entirely wrong — the soil and climate around Stevensville, Hamilton, and Florence did support excellent fruit — but the boosters substantially overstated the ease, the yields, and the market access.\n\n## The Big Ditch and the speculation\n\nThe Bitter Root Irrigation Company's Big Ditch, completed in 1907, delivered water to roughly 25,000 acres of bench land. Brochures printed in Chicago and distributed on the Northern Pacific promised orchardists $1,000-per-acre profits on McIntosh and Wagener apples. Thousands of newcomers from the Midwest and East bought land, planted trees, and waited.\n\n## The collapse\n\nThe boom lasted about fifteen years. A combination of late frosts, codling moth infestations, price crashes driven by cheaper Washington State production, and the plain difficulty of dry farming in a valley with shorter seasons than the promotional materials admitted ended the commercial apple economy by the early 1920s. Many homesteaders walked away from their land. The Bitter Root Irrigation Company went bankrupt.\n\n## What remained\n\nThe Bitterroot still grows apples — individual orchards, a handful of commercial ciders, and thousands of backyard trees planted by homesteaders a century ago and never removed. Western Cider in Missoula uses historic Bitterroot varieties. The valley's bench lands that failed as commercial orchards became dry-land farms, then pasture, and in many cases the rural residential subdivisions that give the Bitterroot its current character. A long row of crabapple trees along a ranch fence line is usually all that marks the speculative dream.`,
  },
  {
    headline: "Missoula's Streetcar Era — Tracks on Higgins",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Missoula_Electric_Railway",
    body: `## Electric cars on a mountain-valley street\n\nFrom 1910 to 1932, Missoula operated an electric streetcar system — the Missoula Electric Railway — that ran tracks down Higgins Avenue and out to several residential neighborhoods. The system was modest by urban standards, but for a city of 12,000 people ringed by mountains, it was a genuine transit network that shaped where people lived and how they moved.\n\n## The routes and the neighborhoods they made\n\nThe streetcar lines ran from the Northern Pacific Depot on the Northside, across the Higgins bridge, and out toward the University District, Rattlesnake, and South Higgins. The University District's development as a dense residential neighborhood — students, professors, and working families within walking distance of the University of Montana — was directly supported by the streetcar. Properties along the lines sold faster and for more money, and the neighborhood grid still reflects the transit corridors of a century ago.\n\n## The end of the line\n\nThe Great Depression, automobile competition, and the economics of maintaining rails in a small city ended the Missoula Electric Railway in 1932. The tracks were torn up, the cars sold, and the routes converted to bus service. This pattern — cities abandoning streetcar systems in the 1920s and 1930s in favor of buses and cars — was nearly universal across America, and nearly every American city that did it has spent the decades since reconsidering.\n\n## A ghost in the asphalt\n\nAn occasional stretch of Higgins or Front Street reveals paving stones and rail beds beneath the asphalt during road work. The streetcar's route is still visible in the slight grade changes on south Higgins, and the University District neighborhoods along the old lines remain the densest and most walkable in the city.`,
  },
  {
    headline: "Washington-Grizzly Stadium — How Missoula Became a Football City",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Washington%E2%80%93Grizzly_Stadium",
    body: `## A stadium that grew with the game\n\nWashington-Grizzly Stadium opened in 1986 with a capacity of roughly 12,000 — a modest facility for a Division I-AA football program in a city of 35,000. By the early 2000s, after two national championships and a sustained run of playoff success, it had been expanded four times to hold more than 25,000 fans, making it one of the largest stadiums in the Football Championship Subdivision and one of the loudest small-college football venues in the country.\n\n## Why it became a civic institution\n\nGrizzly football in Missoula is not just a university sport — it is a community event that fills the city every fall Saturday. The tailgate culture stretches from the parking lots on South Avenue to downtown bars and back again; the student section, the alumni, and the local families who have held the same seats for twenty years all mix in the bleachers in a way that is relatively rare in major college football. The stadium's location on the south side of campus, visible from the Clark Fork trail and backed by Mount Sentinel, makes it one of the most striking athletic venues in the Mountain West.\n\n## Championships and the 1995 turning point\n\nThe 1995 national championship — won under quarterback Dave Dickenson at Chattanooga — was the moment Missoula became serious about football infrastructure. A new stadium expansion began almost immediately; the lights, the scoreboard, and the locker rooms followed. The Grizzlies won another national championship in 2001 and made the playoffs every year from 1995 to 2009, turning the stadium into a destination.\n\n## What it gave the city\n\nFall Saturdays in Missoula have a rhythm: farmers' market in the morning, game at noon, brewery by four. The stadium is the anchor of that rhythm, and its success is the reason Missoula's sports identity is built around Griz football rather than any professional team.`,
  },
  {
    headline: "Fort Missoula's WWII Internment — Italian Seamen and Japanese Americans",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Fort_Missoula",
    body: `## A peacetime fort becomes a wartime prison\n\nWhen the United States entered World War II in December 1941, Fort Missoula — a sleepy Army post on the south side of the city — was quickly repurposed as a detention facility. It became one of the largest internment camps in the Mountain West, holding two distinct populations under very different conditions.\n\n## Italian merchant seamen\n\nIn the immediate days after Pearl Harbor, the U.S. seized Italian merchant ships in American ports, along with their crews. More than 1,000 Italian seamen — civilian workers who had been at anchor in New York, New Orleans, and other harbors — were transported to Fort Missoula in early 1942. Their internment was a legal novelty: as enemy nationals but non-combatants, they were held in conditions that, while restricted, included organized sports, gardens, a camp newspaper, and theatrical productions.\n\n## Japanese American men\n\nSeveral hundred Japanese American men, many of them community leaders and Japanese-language teachers from the West Coast, were also held at Fort Missoula in 1942 before being transferred to other camps. Unlike the Italian seamen, they were American citizens or legal residents facing a blanket presumption of disloyalty. The difference in treatment between the two groups reflected the racial dimensions of wartime internment policy.\n\n## After the war\n\nSome Italian internees remained in Missoula after the war, married local women, and contributed to the city's postwar life. The Japanese American community's experience is remembered less prominently but has been preserved in oral histories at the Mansfield Library and at the Historical Museum at Fort Missoula. The museum occupies the original fort buildings and includes a permanent exhibit on the internment years — a careful, honest account of one of the city's most complicated chapters.`,
  },
  {
    headline: "Before Missoula: The Hellgate Trading Post and the Birth of a River Town (1860)",
    kind: "history",
    body: `## A trading post at the canyon's mouth\n\nBefore there was a Missoula, there was Hellgate — a rough settlement at the mouth of the canyon east of the modern city, where French-Canadian trappers and early American traders met with the Salish and Pend d'Oreille peoples who had long used the confluence as a trading and camping ground. By the late 1850s, a trading post had taken root there, run first by Richard Grant and later by the partners who would become Missoula's founders.\n\n## Higgins, Worden, and the move upstream\n\nChristopher Higgins and Francis Worden established themselves at the Hellgate location in 1860, selling provisions to miners headed for the gold camps along the Clark Fork and its tributaries. Within four years they understood that Hellgate's location was inferior — too exposed, too close to the canyon's winds, without the agricultural potential of the broader valley floor upstream. In 1864 they moved their operation to the site that became modern Missoula, calling the new location Missoula Mills.\n\n## What they left behind\n\nThe original Hellgate site, now in the industrial and residential strip east of Missoula along Highway 200, has no marker and no notable remains. The location's importance is preserved entirely in its name: Hellgate Canyon, Hellgate High School, the Hellgate Treaty, and the Hellgate chapter of the Daughters of the American Revolution all descend from a rough trading post that lasted barely a decade.\n\n## A founding moment\n\nThe move upstream in 1864 is as close as Missoula comes to a founding moment. By choosing the confluence of the Clark Fork and Rattlesnake Creek as their new location, Higgins and Worden committed the city to the grid it still occupies. The Higgins Avenue bridge and the downtown blocks north and south of the Clark Fork rest on the decision two traders made in the winter of 1863–64.`,
  },
  {
    headline: "Lewis and Clark Come Through: The Lolo Trail (1805–1806)",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Lolo_Trail",
    body: `## Two visits to the same trail\n\nThe Lewis and Clark expedition crossed the Bitterroot Mountains via the Lolo Trail twice: once in September 1805 on the westward journey to the Pacific, and again in June 1806 on the return. Both crossings passed through what is now the Missoula area, and the expedition's journals provide the earliest written European-American account of the landscape that became the city.\n\n## The 1805 crossing\n\nThe expedition entered the Bitterroot Valley from the south in early September 1805, following the river northward toward what is now Missoula, then turning west toward Lolo Pass. The mountains were already showing snow at high elevation; the party was low on food and had traded several horses. They camped near the mouth of Lolo Creek — a site within walking distance of modern Missoula — before beginning the grueling mountain crossing that nearly cost them the expedition.\n\n## A Salish encounter near Missoula\n\nBefore entering the mountains, Lewis and Clark met with a band of Salish people near present-day Lolo, Montana. The meeting was friendly — the Salish provided horses and food — and is one of the earliest documented encounters between American explorers and the people who had lived in the Missoula valley for millennia. The captains noted the Salish's unusual speech and their willingness to trade.\n\n## The 1806 return\n\nReturning east in June 1806, the expedition followed the Lolo with Nez Perce guides after being blocked by deep snow at the pass. They moved through the Missoula area in mid-June and split into separate parties for the return to the Missouri. Clark's group descended the Bitterroot Valley; Lewis's group passed through the Blackfoot.\n\n## A route still walkable\n\nU.S. Highway 12 parallels the Lewis and Clark route, and the Lolo Pass Visitor Center interprets both the Indigenous and exploration histories of the corridor. The landscape they moved through — the broad valley, the mountain wall to the west — is recognizable from their journals today.`,
  },
  {
    headline: "CutBank — The Literary Magazine That Outlasted the Program That Made It",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/CutBank",
    body: `## A magazine born in a workshop\n\nCutBank, the literary magazine of the University of Montana's creative writing program, was founded in 1973 — a product of the workshop culture that Richard Hugo had built through his first decade at UM. The magazine was student-edited from the beginning, and it published early work by writers who later became significant: fiction, poetry, and essays from the expanding creative writing community in Missoula and from writers across the country who submitted to a journal that had built, surprisingly quickly, a serious national reputation.\n\n## What the name means\n\nA cutbank is the outer, eroded bank of a river meander — the concave wall where the current is fastest and the earth cuts away in layers. The word is common in Montana English and evocative of the Clark Fork, which cuts its own banks through the valley in several places. As a name for a literary magazine, it suggests the sense of exposure and revelation that the best writing produces.\n\n## Five decades of continuous publication\n\nCutBank has been published continuously since 1973 — a remarkable run for a student-edited literary journal at a mid-sized university. Its alumni list includes contributors who have gone on to publish in The New Yorker, Poetry, Tin House, and the major national venues. Its editorial history tracks the shifts in American literary fashion from the post-Hugo regionalism of the 1970s through the theoretical 1990s to the hybrid forms of the present.\n\n## A Missoula institution\n\nCutBank operates out of the Liberal Arts Building on campus, publishes two issues a year, and accepts unsolicited submissions from writers across the country. For fifty years it has been the primary venue through which UM's creative writing program has demonstrated its ambitions to a national audience. The magazine and the Missoula literary tradition it represents are now effectively inseparable.`,
  },
  {
    headline: "Missoula's Clark Fork River — The City's Central Character",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Clark_Fork",
    body: `## A river that made the valley\n\nThe Clark Fork River begins at the Silver Bow Creek confluence near Warm Springs, gathers the Bitterroot and Blackfoot near Missoula, and runs northwest to Pend Oreille Lake in Idaho — the largest river by volume in Montana. Missoula sits at the Clark Fork's broadest valley, where the river slows and spreads before entering Hellgate Canyon to the east. The city exists because the river made the valley habitable.\n\n## A century of industrial injury\n\nFor most of the 20th century the Clark Fork was one of the most contaminated rivers in the American West. Mining waste from the Butte-Anaconda corridor — arsenic, copper, lead, and zinc — traveled downstream in every flood and settled into the floodplain soils and river sediments for a hundred miles. The Clark Fork/Milltown Superfund complex, listing more than 100 miles of the river and its tributaries, remains the largest Superfund site in the country by area.\n\n## Recovery and what it looks like\n\nThe 2008 Milltown Dam removal began a new chapter. The Clark Fork Coalition, founded in 1985, has coordinated sediment cleanup, water quality monitoring, and public advocacy for three decades. The river's fish populations have recovered in many reaches; bull trout, once nearly absent below Milltown, have returned. The Riverbank Trail, Caras Park, Brennan's Wave, and dozens of access points have given Missoula a relationship with its river that the industrial era denied.\n\n## Water rights and the future\n\nThe Clark Fork's water rights are among the most contested in Montana. The Confederated Salish and Kootenai Tribes' water compact, under negotiation for decades, represents one of the largest tribal water rights settlements in U.S. history and will fundamentally reshape how water is allocated across the Clark Fork basin. The river's future is as politically important as its past.`,
  },
  {
    headline: "Missoula's Milwaukee Road — The Electrified Railway and Its Ruins",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Chicago,_Milwaukee,_St._Paul_and_Pacific_Railroad",
    body: `## A second railroad with a different idea\n\nMissoula was already a Northern Pacific town when the Chicago, Milwaukee, St. Paul and Pacific Railroad — the Milwaukee Road — arrived in the early 1900s as competition. The Milwaukee built its own yards and depot north of the Clark Fork and attempted to undercut Northern Pacific rates on Midwest freight. For a period in the 1910s and 1920s, Missoula had two competing transcontinental railroads.\n\n## Electrification across the mountains\n\nThe Milwaukee Road made an extraordinary engineering decision: it electrified its mountain divisions, including the segment through Missoula and across the Bitterroot Mountains, using overhead wire and electric locomotives. The electric system ran from Harlowton, Montana, to Avery, Idaho — one of the most dramatic electrified railway operations in North America. Electric locomotives pulled freight and passenger trains through Hellgate Canyon and over the divide while the competing Northern Pacific burned coal and diesel.\n\n## Abandonment and the Kim Williams Trail\n\nThe Milwaukee Road went bankrupt in 1977 and abandoned its Pacific Extension in 1980. The rails were pulled. The Missoula segment of the old Milwaukee right-of-way, running along the south wall of Hellgate Canyon east of the University, became the basis for the Kim Williams Nature Trail — a rails-to-trails conversion that turned an abandoned industrial corridor into one of Missoula's most beautiful walking paths.\n\n## What remains\n\nThe old Milwaukee depot on the Northside is a restaurant. The catenary towers that supported the overhead wires are gone, but concrete foundations and retaining walls remain in the canyon east of town. The Kim Williams Trail follows the grade daily, carrying runners and cyclists over ground where electric trains once ran silently through Hellgate.`,
  },
  {
    headline: "The Civilian Conservation Corps in Missoula — Building the Forest City",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Civilian_Conservation_Corps",
    body: `## A federal work program that reshaped western Montana\n\nThe Civilian Conservation Corps, created by the Roosevelt administration in 1933, put unemployed young men to work on public lands across the country. In western Montana, the CCC was one of the most consequential federal programs of the 20th century — not just as an economic measure, but as a physical force that built trails, campgrounds, fire lookouts, bridges, and the infrastructure that makes the Missoula area's public lands usable today.\n\n## The camps around Missoula\n\nSeveral CCC camps operated in and around Missoula County through the late 1930s, supervised by the U.S. Forest Service and the Montana State Forester. The camps sent crews into Pattee Canyon, the Rattlesnake drainage, the Lolo National Forest, and the Bitterroot. They built the Pattee Canyon picnic area and initial trail system, reshaped sections of the Clark Fork banks near what is now McCormick Park, and constructed fire lookouts on the ridges east of town.\n\n## What they built that still stands\n\nThe Lolo National Forest's backcountry infrastructure — the trails through the Bob Marshall Wilderness approaches, the ranger station buildings at trailheads, the bridges over streams that would otherwise require fords — is substantially a CCC legacy. The Pattee Canyon trails that Missoulians run and ski on were cleared by CCC crews in the 1930s. The picnic shelter at the top of the canyon was built by CCC hands.\n\n## A New Deal in the mountains\n\nThe CCC represented an unusual federal investment in the physical infrastructure of the public lands, and its effects have lasted nearly a century. The young men who enrolled — mostly from East Coast and Midwest cities with no outdoor background — sent money home to struggling families, learned trades, and built things that their grandchildren now use every summer weekend in the hills above Missoula.`,
  },
  {
    headline: "Missoula's Northside — A Railroad Neighborhood That Survived",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Missoula,_Montana",
    body: `## Built for the railroad, changed by everything else\n\nThe Northside neighborhood — north of the Clark Fork, running from the old Northern Pacific yards west toward California Street — was built between the 1880s and 1920s to house the families of railroad workers, mill hands, and craftsmen who kept the NP's Missoula division running. The grid of small frame houses, modest churches, and working-class social institutions gave the Northside a character distinct from the more prosperous University District and the downtown commercial blocks south of the river.\n\n## Immigrant communities and their buildings\n\nThe Northern Pacific recruited immigrant workers — Italian, Irish, Scandinavian, and Polish families who settled in the Northside blocks nearest the yards. Their churches, fraternal halls, and cemeteries still stand in various states of preservation. St. Anthony's Church on Spruce, the old Sons of Norway lodge, and St. Mary's Cemetery on the hill above the Bitterroot crossing all document the ethnic diversity that the railroad brought to a Montana city that is stereotyped as homogeneous.\n\n## Decline, then revival\n\nThe Northside struggled economically after the railroads' decline and the timber industry's collapse. In the 1970s and 1980s it was one of Missoula's most economically distressed neighborhoods. The past two decades have brought steady investment, partly driven by housing demand from a growing city: craftsman bungalows restored, vacant lots filled with infill housing, new businesses along the commercial strips on Russell and California.\n\n## What it is now\n\nThe Northside is still the most affordable dense neighborhood in Missoula. Its proximity to the Rattlesnake trail system, the Clark Fork, and downtown makes it attractive to the young, and its modest housing stock makes it accessible to the working-class residents who still form its majority. The neighborhood's history is most visible in its oldest church buildings and in the railroad infrastructure — depots, roundhouse foundations — that still marks the ground north of the river.`,
  },
  {
    headline: "The 1891 Removal of the Bitterroot Salish — Montana's Trail of Tears",
    kind: "history",
    sourceUrl: "https://mhs.mt.gov/education/bios/charlo.pdf",
    body: `## A forced march that shaped the Missoula valley\n\nIn October 1891, a column of U.S. Army soldiers from Fort Missoula escorted Chief Charlo and approximately 150 Bitterroot Salish men, women, and children north on a sixty-mile march from the Bitterroot Valley to the Flathead Reservation near Jocko. The removal was the culmination of forty years of broken promises, forged documents, and steadily worsening conditions for a people whose homeland lay immediately south of Missoula.\n\n## What led to it\n\nThe Hellgate Treaty of 1855 had promised the Bitterroot Salish a survey to determine their permanent home. The survey was indefinitely delayed; the U.S. issued an executive order for removal in 1871; Charlo refused and remained. For twenty years, as the buffalo herds disappeared and squatters encroached, his people grew poorer while the government stalled. By 1889, starvation threatened the band. Charlo finally agreed to leave in exchange for the promise of good farmland on the reservation.\n\n## The march itself\n\nContemporary accounts describe the October 1891 removal as poorly organized and emotionally devastating. The soldiers provided inadequate supplies for the journey; some Salish families had to leave behind property and livestock. Charlo reportedly did not speak during the march and arrived at the Flathead Reservation embittered. He spent the rest of his life trying to hold the government to its promises about the quality of the reservation land he had been given.\n\n## The long shadow\n\nThe removal is commemorated at the Historical Museum at Fort Missoula and in the records of the Confederated Salish and Kootenai Tribes. The Bitterroot Valley, now one of Montana's fastest-growing residential areas, was transformed by the removal from a Salish homeland to a predominantly settler landscape in a single generation. The Salish names for its features, and the sovereignty of the CSKT sixty miles north, are the most visible reminders of what was taken.`,
  },
  {
    headline: "Missoula's Public Library — From Carnegie to Community",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Missoula_Public_Library",
    body: `## A Carnegie library and what followed\n\nMissoula's first dedicated public library building opened in 1903, funded by a $12,500 Carnegie grant — one of the more than 2,500 library buildings Andrew Carnegie financed across the English-speaking world. The building stood at Pine and Pattee until it was demolished in the 1970s, replaced by a larger facility that served the city through decades of growth before it too became inadequate.\n\n## A new library for a growing city\n\nAfter years of planning and public debate about location and design, the new Missoula Public Library opened in 2021 in a purpose-built facility on East Main Street, across from Caras Park on the Clark Fork. The building, designed to achieve LEED Platinum certification, features extensive glass overlooking the river, flexible community spaces, a children's wing, and a local history collection that includes maps, photographs, and documents dating to the territorial period.\n\n## More than books\n\nThe Missoula Public Library has long functioned as a community center in ways that go beyond its collection. It houses English language learning programs for the city's refugee and immigrant communities, job-search and technology assistance, meeting rooms used by nonprofits and neighborhood groups, and one of the more active children's programming calendars in the Mountain West. In a city with one of the highest rates of library card ownership in Montana, it is also just a library — a place where people come to read.\n\n## A civic landmark on the river\n\nThe 2021 building's location between downtown and the Clark Fork trail system has made it a civic anchor in a stretch of the riverfront that has been transformed over the past thirty years. The old Carnegie building is gone, but the tradition it represented — a public collection, available to anyone, in a building worth entering — has found its best expression yet in the new building on East Main.`,
  },
  {
    headline: "The Western Montana Fair — A Century of August in Missoula",
    kind: "history",
    sourceUrl: "https://www.missoulacountyfairgrounds.com/2026-western-montana-fair",
    body: `## A fair older than the cars that now fill the parking lot\n\nThe Western Montana Fair has been held in Missoula every August since the early 1900s. It began as an agricultural fair — livestock judging, produce competitions, and the kind of communal gathering that marked the harvest season across rural America — and over more than a century evolved into one of the largest county fairs in Montana.\n\n## From airfield to fairground\n\nMissoula County purchased the current fairground site in 1913 for $16,000. The land had served briefly as one of Missoula's earliest airfields; in 1913, it was converted to a permanent fair site with permanent barns, a grandstand, and a track. The site on North Reserve Street still occupies that original purchase, though the buildings, track, and grandstand have been replaced and expanded many times.\n\n## What the fair means\n\nThe Western Montana Fair's character is distinctly agricultural at its core — the 4-H livestock competitions, the open class produce judging, and the draft horse pulling contest belong to a tradition that connects modern Missoula to the farming and ranching communities of Ravalli, Mineral, Sanders, and Lake counties that the fair serves. The midway, the concerts, and the carnival rides are later additions to a gathering that began as a place to compare cattle.\n\n## An August ritual\n\nFor Missoula residents, the fair is one of summer's fixed points. The demolition derby in the infield, the funnel cake stand that occupies the same corner every year, and the evening grandstand concerts have accumulated the kind of collective memory that makes a community fair genuinely communal. The fairgrounds also host rodeos, trade shows, and political events the rest of the year — they are a year-round public space whose August moment is the most crowded and the most itself.`,
  },
  {
    headline: "Missoula's Journalism School — Reporters for the Mountain West",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/University_of_Montana_School_of_Journalism",
    body: `## A school founded on the idea of local news\n\nThe University of Montana School of Journalism was established in 1914, one of the first dozen journalism schools in the United States. Its founding reflected a conviction that the Mountain West needed trained reporters — people who understood the specific economy, politics, and landscape of a region that the eastern press consistently misrepresented. For more than a century it has been the primary training ground for journalists who have worked at Montana and regional papers, television stations, and national outlets.\n\n## A curriculum built on practice\n\nUM's journalism program has always emphasized hands-on reporting. Students cover Missoula city government, the Missoula County courthouse, UM athletics, and state and regional issues for print and broadcast outlets that publish or air real journalism for real audiences. The Montana Kaimin, the student newspaper that has published continuously since 1898, remains one of the most respected college daily newspapers in the West.\n\n## Notable alumni and faculty\n\nThe school's alumni include television journalists, documentary filmmakers, editors at major regional and national publications, and the founders of Montana-specific outlets like the Montana Free Press. Kim Williams, the naturalist and NPR commentator, was associated with the school's journalism programs. The school's emphasis on environmental journalism, driven by UM's proximity to the Lolo National Forest and the Clark Fork Superfund, has produced several generations of reporters who specialize in public lands and natural resources coverage.\n\n## What it means for local news\n\nIn an era when local news organizations across the country are collapsing, UM's journalism school is one reason Missoula has more and better local journalism than most comparable cities. The Montana Free Press, the Missoulian, and MTPR all regularly hire UM graduates or collaborate with the school's reporting programs. A journalism school in a mountain city is part of why Missoula's civic life is as legible as it is.`,
  },
  {
    headline: "Missoula's Chinatown — The Community That Was Erased",
    kind: "history",
    sourceUrl: "https://scholarworks.umt.edu/cgi/viewcontent.cgi?article=1042&context=montanajournalism",
    body: `## A Chinese community in a railroad city\n\nLike most Western railroad and mining cities, Missoula had a Chinese community in the late 19th century — workers who had come west with the transcontinental railroad construction and stayed on to run laundries, restaurants, and gardens. At its largest, Missoula's Chinatown, located in the blocks near the NP railroad yards on the Northside, may have housed several hundred residents.\n\n## Work and exclusion\n\nChinese workers in Missoula, as elsewhere in the West, occupied a narrow economic niche defined by the work white workers refused — laundry, domestic service, market gardening, and small-scale food service. They were excluded from mining claims by law and custom, barred from most skilled trades, and subject to the Chinese Exclusion Act of 1882, which prohibited new immigration from China and denied naturalization to those already here.\n\n## The gradual disappearance\n\nMissoula's Chinese community shrank steadily after the 1880s, as the railroad construction phase ended, as exclusion laws limited community renewal through immigration, and as anti-Chinese sentiment — sometimes violent — pushed families out of the region. By the early 20th century the community had largely dispersed, and by mid-century it had essentially disappeared from the city's visible life.\n\n## What remains and what doesn't\n\nNo buildings from Missoula's Chinatown survive. The neighborhood's location has been absorbed into the Northside's industrial and residential grid. The most substantial archival record is held at the Mansfield Library and in local newspaper files from the territorial and early statehood periods. Missoula's Chinese community is one of the city's invisible histories — a real and substantial presence for a generation, then quietly erased. A growing body of regional historical work has begun to recover it.`,
  },
  {
    headline: "Missoula's Northside Norwegian Community — Churches, Skiing, and the Sons of Norway",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Missoula,_Montana",
    body: `## Scandinavians who came for the railroad and stayed for the mountains\n\nAmong the immigrant communities that built the Northside in the railroad era, Scandinavian workers — Norwegian, Swedish, and Finnish families — were among the most numerous and the most organizationally active. They came for railroad and timber work in the 1880s and 1890s, settled in the frame houses north of the Clark Fork, and established the social institutions that gave their community cohesion.\n\n## The Sons of Norway and community life\n\nThe Missoula chapter of the Sons of Norway, a fraternal organization founded in Minneapolis in 1895, was one of the most active ethnic mutual-aid societies in the city through the early 20th century. The lodge on the Northside hosted cultural events, provided modest financial support to sick or injured members, and maintained the connections between Missoula's Norwegian community and the wider Scandinavian-American network. Similar organizations served Swedish and Finnish workers in the same neighborhoods.\n\n## Skiing — a Norwegian export to Montana\n\nNorwegian and Swedish immigrants brought skiing to Missoula and western Montana earlier than is often recognized. Cross-country skiing and simple downhill on local hills was practiced by Scandinavian families in the Northside and Rattlesnake as early as the 1890s. The development of organized alpine skiing at Snowbowl, Marshall, and Lolo Peak all drew on community norms established by Scandinavian immigrants who had grown up skiing in Norway and Sweden as a practical means of winter travel.\n\n## A community absorbed\n\nBy the mid-20th century, Missoula's Scandinavian community had been largely absorbed into the broader white working-class identity of the Northside. Norwegian surnames are common in the city's older families, and the skiing culture the immigrants brought has become simply Missoula's skiing culture — a mountain city's natural birthright, in the way that skiing traditions often make themselves seem.`,
  },
  {
    headline: "Missoula's River Culture — Kayaking, Floating, and the Clark Fork's Recreation Revolution",
    kind: "history",
    sourceUrl: "https://paddlingmag.com/stories/culture/brennans-wave-missoula/",
    body: `## A river the city turned its back on — and then turned toward\n\nFor most of the 20th century, the Clark Fork through downtown Missoula was an industrial corridor — the railroad ran along its north bank, the downtown faced away from it, and the water quality made recreational use uninviting. The transformation from industrial margin to recreational heart happened in roughly one generation, from the late 1980s to the present.\n\n## The Caras Park transformation\n\nThe creation of Caras Park in the 1990s — converting railroad yard and parking lot to public green space and amphitheater — was the first major step. The Riverbank Trail followed, linking the park east to the University of Montana and west to McCormick Park and the Northside. The trail system connected neighborhoods that had previously been riverbank-adjacent but not river-facing.\n\n## Brennan's Wave and river sports\n\nBrennan's Wave, completed in 2006, transformed the Clark Fork into an active play zone. Kayakers, river surfers on modified surfboards, and stand-up paddleboarders have used the wave daily through the ice-free season since its opening. The wave is visible from Caras Park and the farmers' market and has become a symbol of Missoula's identity as a river city in a way that the Riverbank Trail, for all its use, never quite did — the spectacle of surfing in downtown Montana is genuinely arresting.\n\n## Float culture and summer identity\n\nFloating the Clark Fork on inner tubes — the Milltown to Brennan's run, the Reserve Street put-in to Caras take-out — is one of Missoula's definitive summer activities, practiced by UM students, families, and adults who have been doing it for forty years. On a July afternoon, the river carries hundreds of floaters, the banks are lined with spectators, and the old industrial corridor is the most social space in the city.`,
  },
];
