/**
 * History desk content bank. Each entry is ~300 words of original
 * ZooTown-written prose about Missoula's past. Wikipedia / archive links are
 * cited as references (the article body is ours, not theirs).
 *
 * The daily writer pulls these in order and stops when the bank is exhausted.
 * Admin can extend the bank or write new entries directly through the UI.
 */
import type { DraftArticle } from "./writer";

export const HISTORY_BANK: DraftArticle[] = [
  {
    headline: "The Hellgate Treaty of 1855",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Hellgate_treaty",
    body: `## A treaty signed in a tense valley\n\nIn July 1855, Territorial Governor Isaac Stevens met with leaders of the Salish, Pend d'Oreille, and Kootenai peoples at a cottonwood grove near the mouth of the Bitterroot Valley. The meeting, brokered with chronically poor translation, produced what came to be known as the Hellgate Treaty.\n\n## What the document said\n\nThe treaty consolidated the three tribes onto the Flathead Reservation north of Missoula and opened the rest of the valley to settlement. Chief Victor of the Bitterroot Salish refused to sign away his people's home in the Bitterroot itself, securing a clause that promised a survey to determine whether the Bitterroot or Jocko valley would become the permanent reservation. That survey never happened in good faith; in 1891 the U.S. Army forcibly removed the Bitterroot Salish to the Jocko, a march remembered as one of Montana's deepest injustices.\n\n## Why it still shapes Missoula\n\nThe treaty's footprint is everywhere in modern Missoula. Place names — Lolo, Frenchtown, Arlee, Ravalli — are Salish or trace back to figures involved in the treaty era. Land use disputes from water rights to highway easements still cite Hellgate. And the Confederated Salish and Kootenai Tribes remain a sovereign government whose territory borders the city, with growing cultural and economic influence on the region.\n\n## A note on language\n\nThe city's name is itself a treaty-era artifact: Missoula comes from the Salish term often rendered nemissoolatakoo, "place of frozen water," describing the narrow gap east of town where ambushes once made the canyon a feared crossing. The English version, Hellgate, comes from French trappers' translation of the Salish warning. Two languages, the same warning, the same gap.`,
  },
  {
    headline: "The Big Burn of 1910",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Great_Fire_of_1910",
    body: `## Two days that defined American firefighting\n\nOn August 20 and 21, 1910, a hurricane-force dry wind swept across the northern Rockies and turned thousands of smoldering fires into a single firestorm. Three million acres burned across Idaho and western Montana in roughly 48 hours. Eighty-seven people died, most of them young U.S. Forest Service firefighters and the immigrant laborers who fought alongside them.\n\n## Missoula at the center\n\nMissoula was the staging ground. The brand-new Forest Service, headquartered in the Northern Rockies Region from offices on East Broadway, sent crews into the Bitterroot, the Coeur d'Alene, and the St. Joe. Trains pulled into the Missoula yards carrying survivors, the burned, and the dead. A makeshift morgue opened downtown. The city's hospitals filled to capacity.\n\n## The legacy in policy\n\nThe Big Burn changed how the United States manages forests. Convinced that aggressive suppression could prevent another catastrophe, the Forest Service committed to fighting every fire on every acre — a policy that defined a century of land management and that researchers now believe contributed to today's bigger, hotter fires by allowing fuels to accumulate. The Smokejumpers, headquartered at Missoula's Aerial Fire Depot since 1954, trace their lineage straight to the lessons of 1910.\n\n## Where to see it\n\nThe Smokejumper Visitor Center off Highway 10 keeps photographs, gear, and oral histories from the 1910 fires and the decades of crews that followed. Granite Pass north of Lolo and the burn scars visible from the Lolo Trail still bear the geometry of that fire more than a century later — strips of even-aged lodgepole pine in country that would otherwise look very different.`,
  },
  {
    headline: "How the Northern Pacific Railroad Reshaped Missoula",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Northern_Pacific_Railway",
    body: `## A town becomes a hub\n\nMissoula existed before the Northern Pacific arrived in 1883, but the town that exists today was largely drawn by the railroad. The NP chose the Missoula valley as a division point — a place where crews changed, locomotives were serviced, and freight was reorganized for the climb over Mullan Pass to the east and the long descent into Idaho to the west.\n\n## The Northside takes shape\n\nThe yards, roundhouse, and shops went in north of the Clark Fork. Worker housing followed: the Northside neighborhood's grid of small frame houses dates almost entirely to the railroad's first two decades in town. Many of the residents were Italian, Irish, and Scandinavian immigrants drawn by steady wages. Their churches, social halls, and cemeteries — St. Mary's Cemetery, the old Polish Hall, the Sons of Norway lodge — give the Northside a cultural depth most visitors never see from the highway.\n\n## What the railroad moved\n\nLumber, livestock, copper from Butte, and people. Missoula was the gateway to the Bitterroot apple boom, and refrigerated railcars sent western Montana fruit to Minneapolis and Chicago. The Anaconda Company's copper traveled east through Missoula on its way to East Coast refineries. The University of Montana's growth in the early 1900s depended on students and faculty arriving by train.\n\n## What's left today\n\nThe Northern Pacific Depot at the north end of Higgins still stands as a restaurant and event space — an Italianate Revival reminder of how central the railroad once was. BNSF, the NP's modern descendant, still runs freight through town, and the whistle at the Higgins crossing remains one of Missoula's most familiar nighttime sounds.`,
  },
  {
    headline: "Fort Missoula and the Buffalo Soldiers' Bicycle Corps",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/25th_Infantry_Regiment_Bicycle_Corps",
    body: `## A fort built for a long-vanished mission\n\nThe U.S. Army established Fort Missoula in 1877 to keep an eye on the recently displaced Salish and to provide a base for operations during the Nez Perce War. By the 1890s its original purpose had faded, and the post took on stranger and more interesting roles than its founders ever imagined.\n\n## A bicycle as a war machine\n\nIn 1896 the 25th Infantry Regiment, an all-Black unit under white officers, was stationed at Fort Missoula. Lieutenant James Moss convinced the Army to test whether bicycles could replace horses for long-distance reconnaissance. The Bicycle Corps rode 800 miles to Yellowstone and back over rough mountain roads — and then, in 1897, made a 1,900-mile journey from Missoula to St. Louis on single-speed bikes weighing about thirty pounds, carrying their own gear and rations.\n\nThey averaged better than fifty miles a day across the Great Plains in July. The experiment proved the concept and was promptly forgotten by an Army that preferred horses. The soldiers themselves, members of one of the famed Buffalo Soldier regiments, returned to a country that gave them little credit.\n\n## The fort's later lives\n\nDuring World War II, Fort Missoula became an internment site for Italian merchant seamen seized in U.S. ports and for several hundred Japanese-American men taken from the West Coast. Many of the Japanese-American detainees were later transferred to camps farther inland; some Italian internees stayed in Missoula and became part of the community after the war.\n\nThe Historical Museum at Fort Missoula now occupies the old post and tells these layered stories — military, civil rights, immigration, and labor — in the same buildings where they happened.`,
  },
  {
    headline: "Higgins Avenue and the Bridge That Made the City",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Higgins_Avenue_Bridge",
    body: `## A bridge before there was much of a town\n\nCaptain Christopher Higgins and his partner Francis Worden ran the trading post that became Missoula. By the 1870s they understood that the future of the settlement depended on linking the south side of the Clark Fork — where the Hellgate trail ran — to the north bank, where the railroad would eventually arrive. The first Higgins Avenue bridge, a wooden toll structure, opened in 1873.\n\n## Three bridges, one location\n\nFloods and decay required replacement; the current concrete arch bridge dates to 1962, with major rehabilitation in the 2000s. The location, however, has stayed the same for 150 years. That continuity is the reason Higgins is Missoula's main street — every successive bridge committed the city to growing along that axis.\n\n## A street with structure\n\nWalk Higgins today and the 19th-century footprint is still legible. The Florence Hotel block, the Wilma Theater, the Missoula Mercantile site (now Mercantile Hotel), the old First National Bank — these are bones of a downtown that was largely built between 1890 and 1925. Many storefronts retain their cast-iron columns and pressed-metal cornices.\n\n## A linear public space\n\nHiggins is also one of the few American downtown streets where you can stand on the bridge, look upstream, and see mountains in every direction. That accident of geography — a bridge framed by Mount Sentinel, Mount Jumbo, and Waterworks Hill — has done more for Missoula's identity than any planning document. River City Roots Festival, the farmers' market, Out to Lunch, the Brewers Festival, and the Christmas Stroll all use the same few blocks year after year, reinforcing the idea that this is the heart of town.`,
  },
  {
    headline: "The University of Montana's Founding",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/University_of_Montana",
    body: `## A campus on a floodplain\n\nThe University of Montana opened in 1895 in temporary quarters downtown, with a charter that made it the state's flagship liberal arts institution. By 1898 the first permanent buildings — Main Hall and Science Hall — were rising on a former orchard at the base of Mount Sentinel.\n\n## Main Hall and the M\n\nMain Hall's bell tower has been the school's symbol since the day it opened. The "M" on the side of Mount Sentinel followed in 1909, originally laid out in whitewashed stones by a forestry class. Generations of students have repainted it; the trail to the M is one of the most-walked footpaths in the state.\n\n## Forestry, journalism, and the long bench\n\nThe College of Forestry, founded in 1913, became one of the country's most respected schools of natural resource management. It produced foresters, ecologists, and writers — including Norman Maclean and a long line of people whose careers shaped the U.S. Forest Service. The School of Journalism, established in 1914, became another distinctive program, training reporters who staffed papers across the West.\n\n## Growth and trouble\n\nThe school grew steadily through the 20th century and quickly during the post-WWII GI Bill era. It absorbed Missoula's economy in important ways: the largest employer in the county, the producer of much of its cultural life, and the institution whose students gave the city its famously young median age.\n\nLike many flagships, UM has wrestled with enrollment declines and budget cuts since 2010. It has also kept its distinctive feel — a smaller campus than its peers, with a quieter rhythm and a fiercer attachment to place. The Oval, the M trail, and the bell from Main Hall remain landmarks not just for the campus but for the city.`,
  },
  {
    headline: "The 1910 Floods and the Building of the Levees",
    kind: "history",
    body: `## A river that built and broke the town\n\nMissoula sits at the confluence of the Clark Fork, the Bitterroot, and the Blackfoot. That geography made it a meeting place for thousands of years before settlement, and it has made the city flood-prone for as long as anyone has lived here. The biggest of those floods, in the spring of 1908 and again in 1910, redrew the riverbank and forced the city's first real engineering response.\n\n## What the 1908 flood did\n\nA combination of heavy snowpack, a warm late-May, and rapid melt sent the Clark Fork well over its banks. The old wooden Higgins bridge survived but barely; the Northern Pacific yards on the north side flooded for days; whole sections of the McCormick Park flats sat under water. Several houses on the Northside were lifted off their foundations and floated downstream.\n\n## The response\n\nFlood-control measures came in fits and starts. The Civilian Conservation Corps reshaped the lower Clark Fork banks in the 1930s. The state and federal governments built levees through the 1940s and 1950s, particularly around the rail yards and what is now McCormick Park. The Milltown Dam, downstream from the city, briefly moderated some peak flows — though it created a long-term sediment and contamination problem that took until its 2008 removal to begin solving.\n\n## What's left\n\nThe levees are why Missoula sits where it does today. They protect tens of millions of dollars of downtown property and allow the river to function as a recreational asset rather than a periodic threat. Brennan's Wave, the Caras Park amphitheater, and the Riverbank Trail all exist because the river is contained. Big floods will come again, and Missoula's flood plans now account for that explicitly.`,
  },
  {
    headline: "The Anaconda Company's Long Shadow",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Anaconda_Copper",
    body: `## A copper company that owned a state\n\nFor most of the 20th century, the Anaconda Copper Mining Company was the dominant economic force in Montana. Anaconda employed tens of thousands across mines, smelters, sawmills, and processing plants, and it owned most of the state's daily newspapers — including the Missoulian, until the chain was sold in 1959.\n\n## Missoula's role in the company's empire\n\nMissoula was not a mining town but a mill town. The Bonner Mill, downstream from the city on the Blackfoot, was the largest sawmill in Montana for much of the century and supplied lumber for Anaconda's mines and the railroads carrying its copper. Smaller mills ran in Frenchtown and at Champion. The wood economy ran on Anaconda's demand for timbers, ties, and construction lumber, and tens of thousands of workers depended on it.\n\n## The environmental cost\n\nUpstream from Missoula, the Clark Fork drains the Butte/Anaconda mining district. A century of unregulated mine waste left arsenic, lead, and copper contamination across the basin. The 2008 removal of Milltown Dam, immediately downstream from the city, was driven primarily by the need to deal with toxic sediment trapped behind it — one of the largest Superfund cleanups in the country.\n\n## What replaced it\n\nWhen Anaconda collapsed in the 1980s, Missoula lost mill jobs at Bonner, Frenchtown, and Champion in quick succession. The city's economy reoriented around the University, healthcare, government agencies, and a growing recreation and tourism sector. The transition was painful and is in some ways still underway: rural families that once worked at the mills did not always find equivalent jobs in town, and parts of the regional economy never fully recovered. But Missoula itself became more diversified, and arguably more resilient, than the Anaconda era allowed.`,
  },
  {
    headline: "The Mansfield Library and the Senator's Quiet Legacy",
    kind: "history",
    body: `## A library named after the longest-serving Senate majority leader\n\nMike Mansfield, a Butte miner turned UM history professor turned U.S. senator, represented Montana from 1953 to 1977 and served sixteen years as Senate majority leader — still the record. When the University of Montana built its central research library in 1979, it was named for him.\n\n## A reading room as civic infrastructure\n\nThe Mansfield Library is the largest research library in Montana, with more than a million volumes and a collection that includes the K. Ross Toole Archives of regional history. It is also the de facto public library of west-central Montana for serious researchers, with access agreements that let community members read materials they could not find anywhere else in the state.\n\n## Mansfield himself\n\nMansfield arrived at the University of Montana in 1933 with no high school diploma — he had left home as a teenager and worked the Butte mines — and earned bachelor's and master's degrees while teaching part-time. He served in Congress for thirty-four years, then spent another eleven as U.S. ambassador to Japan, where he is still remembered for his patient diplomatic style. He returned to Missoula in his final years and remained connected to the university until his death in 2001.\n\n## Why the library matters\n\nThe Mansfield Center, also named for him, runs ethics and public-policy programs that draw national speakers to campus. The library hosts visiting scholars, civic forums, and student research that often touches on Missoula's own history. Generations of Missoulians have used the building as a working office during finals week and a quiet refuge during the long winter. For a senator famous for refusing pomp, the building is a fitting monument — useful, unshowy, and full of light.`,
  },
  {
    headline: "Why Missoula Became a Center of Smokejumping",
    kind: "history",
    body: `## A job invented in the Northern Rockies\n\nSmokejumping — parachuting firefighters into remote terrain — was first tested by the U.S. Forest Service in 1939 at the Seeley Lake Ranger Station, an hour northeast of Missoula. The mountainous, road-less country of the Bob Marshall and the Selway-Bitterroot made traditional ground crews too slow; jumpers could reach a new fire within an hour rather than a day.\n\n## The Aerial Fire Depot\n\nIn 1954, the Forest Service consolidated its smokejumper training and dispatch at a purpose-built facility on Highway 10 west of Missoula. The Aerial Fire Depot was the largest of its kind in the country and remains the operational home of the Missoula Smokejumpers and the Forest Service's main parachute loft. Each year, jumpers from across the West gather there for training before fire season.\n\n## Mann Gulch\n\nThe profession's hardest lesson came on August 5, 1949, when thirteen smokejumpers died in Mann Gulch above the Gates of the Mountains, east of Helena. Foreman Wagner Dodge survived by lighting an escape fire — a now-standard technique that he invented on the spot. The dead included men whose families still live in western Montana. Norman Maclean, whose own father had been a Missoula minister, spent his last years writing Young Men and Fire, a meditation on Mann Gulch that became one of the defining books about wildfire.\n\n## The depot today\n\nThe Smokejumper Visitor Center is open every summer with tours of the loft and a small museum. Jumpers still scramble out of the same hangars to fires across the West. The job has changed — better aircraft, better gear, more sophisticated weather prediction — but the geography is the same, and Missoula remains the place where the trade was invented and where it is still taught.`,
  },
  {
    headline: "Caras Park, the Carousel, and the Reclaiming of the Riverfront",
    kind: "history",
    body: `## A parking lot becomes a park\n\nUntil the late 1980s, the south bank of the Clark Fork in downtown Missoula was a railroad yard, a parking lot, and a string of half-vacant industrial buildings. Caras Park, the open green space and amphitheater at the foot of Higgins, did not exist. The riverfront was something the city had turned its back on.\n\n## A community decision\n\nA series of master plans through the 1980s and 1990s, driven by Mayor Dan Kemmis, the Missoula Redevelopment Agency, and a remarkable amount of volunteer energy, gradually reclaimed the south bank. Brennan's Wave (added in 2006) gave kayakers a downtown play feature; the Riverfront Trail linked Caras to the McCormick Park ballfields and on to the University; the carousel anchored the park's east end starting in 1995.\n\n## A Carousel for Missoula\n\nA Carousel for Missoula is a fully hand-carved, locally built carousel — the first such carousel constructed in the United States in nearly sixty years when it opened. Chuck Kaparich, a local cabinetmaker, organized the project; hundreds of volunteers carved horses, painted scenery, and raised money. It remains one of the city's most distinctive civic objects — a working carousel, free or nearly free to ride, built by the people who live around it.\n\n## What it changed\n\nCaras Park is now the venue for Out to Lunch, River City Roots, the Saturday farmers' market, and most summer festivals. The riverbank is one of the most-used public spaces in the city. The change from rail yard to park happened in less than a generation, almost entirely through volunteer time and small public investments. Visitors who arrive in Missoula today often assume the riverfront was always like this; it was not.`,
  },
  {
    headline: "The 1980s and the Slow Death of the Bonner Mill",
    kind: "history",
    body: `## The biggest mill in the state\n\nThe Bonner Mill, on the Blackfoot River five miles east of Missoula, was for most of the 20th century the largest sawmill in Montana. At peak it employed more than a thousand workers and supplied lumber to the Anaconda Company's mines, to the railroads, and to construction markets across the West.\n\n## The downturn\n\nBy the 1980s, the timber industry across the Northwest was contracting. Old-growth supply on federal lands was tightening; the Anaconda Company collapsed in 1983; cheaper Canadian lumber undercut domestic mills; the spotted owl litigation later in the decade froze additional federal timber sales. Bonner did not close all at once — it changed hands multiple times, ran in shifts, and limped through the early 2000s before the final shutdown in 2008.\n\n## What it meant for Missoula\n\nThe closure of Bonner was the last act in a longer story. The Champion Mill in Frenchtown closed in 2010. Smaller mills around the valley closed earlier. Thousands of mill jobs disappeared from the regional economy over roughly two decades. Many of the affected workers commuted from rural communities — Lolo, Bonner, Frenchtown, Potomac — and the loss was felt unevenly across the area.\n\n## What replaced it\n\nMissoula's economy reoriented around healthcare (St. Patrick's and Community Medical Center became two of the largest employers), the University, Forest Service and other federal agencies, software and outdoor-industry companies, and a growing tourism and recreation sector. The Bonner site itself, after years of remediation, is now an industrial park with a brewery, distilleries, and a riverside event venue. The change is visible: where there were once mountains of sawdust, there are now hop fields and pickleball courts. The transition is incomplete, and the cultural memory of the mills runs deep east of town.`,
  },
  {
    headline: "Hellgate Canyon and the Naming of the City",
    kind: "history",
    body: `## A gap with a fearsome name\n\nEast of downtown Missoula, the Clark Fork River cuts a narrow canyon between Mount Sentinel and Mount Jumbo. The Salish called the spot "place of frozen water" or, in earlier translations, "place of ambush" — the canyon was a chokepoint where war parties from the plains could surprise the valley's residents.\n\nFrench-Canadian trappers in the early 1800s heard the Salish warnings, and translated the name as Porte de l'Enfer — Gate of Hell. English speakers shortened it to Hellgate. The first non-Native settlement in the area, Hellgate Trading Post, sat just below the canyon's mouth.\n\n## A town and its names\n\nFor about a decade in the mid-19th century, the settlement was simply Hellgate. When Christopher Higgins and Francis Worden moved their trading operation upstream to the better-watered site that became modern downtown, they renamed it Missoula Mills — and eventually just Missoula — using a more euphonious version of the Salish name for the same canyon.\n\nSo the city carries two names for the same place: Missoula, the soft Salish form, and Hellgate, the French translation of the Salish warning. Hellgate High School, Hellgate Canyon, and the Hellgate Treaty all use the older, harder name; the city itself uses the gentler one.\n\n## What you can still see\n\nThe canyon is still narrow and still windy. Interstate 90 and the Milwaukee Road rail line both pass through it; the Kim Williams Trail runs the south wall as a footpath. The wind that funnels through Hellgate in winter is what makes downtown Missoula colder than the surrounding country, and it is also why Mount Sentinel's south face stays mostly snow-free even in February. A Salish ambush point is now a daily commute.`,
  },
  {
    headline: "The Wilma Theater and the Vaudeville Era",
    kind: "history",
    body: `## A theater on the river\n\nThe Wilma Theater opened in 1921 at the corner of Higgins and the Clark Fork, built by Bill Simons, a Missoula entrepreneur with a flair for showmanship. Named for his wife Edna Wilma, the seven-story brick structure was the tallest building in Montana for several years and the most ornate theater between Spokane and Minneapolis.\n\n## Vaudeville, then movies, then everything else\n\nThe Wilma's original life was as a vaudeville house. Acts on the western circuit booked through Missoula on their way between Spokane and Salt Lake City. By the late 1920s, with vaudeville fading, the venue converted to a movie palace. A pipe organ, still intact, accompanied silent films. The theater hosted political conventions, school graduations, weddings, and political speeches — the building was a civic space as much as an entertainment one.\n\n## The 1970s and after\n\nLike many downtown theaters in the era of suburban multiplexes, the Wilma struggled through the 1970s and 1980s. It was nearly demolished more than once. A succession of owners and a determined preservation effort kept the doors open. Today the Wilma operates as a concert venue with a busy schedule of touring musicians and comics; it is one of the most acoustically distinctive rooms in the Rocky Mountain West, and a place where Missoula audiences have heard everyone from Willie Nelson to Wilco to Joan Baez.\n\n## Inside the building\n\nThe seven stories above the theater contain apartments, offices, and a basement bar that traces back to the 1920s. The marquee at Higgins and Front, a 1930s addition, is one of the most photographed objects in downtown Missoula. The building's longevity says something about the city: nearly every American town once had a Wilma; Missoula still has its.`,
  },
  {
    headline: "The Milltown Dam Removal",
    kind: "history",
    sourceUrl: "https://en.wikipedia.org/wiki/Milltown_Dam",
    body: `## A century-old dam comes down\n\nIn 2008, after more than a decade of planning and a Superfund process that took years to negotiate, the Milltown Dam at the confluence of the Clark Fork and Blackfoot rivers was removed. It was, at the time, the largest dam removal in U.S. history and one of the largest river restoration projects ever undertaken.\n\n## Why it was built — and why it had to come out\n\nThe original Milltown Dam was completed in 1908 to power a sawmill and later the Anaconda smelter's operations. Over a century, a century of mining waste from Butte and Anaconda had settled into the reservoir behind it — millions of cubic yards of arsenic-, lead-, and copper-laden sediment, the largest concentrated repository of mine waste in the West. A 1996 ice jam threatened to breach the dam and release that toxic load downstream into Missoula's drinking water.\n\nThe federal Superfund process forced the issue. The dam was decommissioned, the contaminated sediment dug out and trucked to a permanent containment site, and the rivers were allowed to re-meander through a restored confluence.\n\n## The result\n\nThe rivers reconnected for the first time in a century. Bull trout, native cutthroats, and other migratory species began moving back upstream. Caras Wildlife Refuge and Sha-Ron Park, both built into the restored confluence, are now among the most heavily used outdoor spaces in the valley. The water quality in the lower Clark Fork has improved measurably.\n\n## What it taught\n\nMilltown became a national reference case for industrial-era river restoration. The project's combination of dam removal, sediment cleanup, and habitat reconstruction influenced similar work on the Elwha in Washington and the Klamath on the Oregon-California border. Five miles east of downtown Missoula, the rivers run free.`,
  },
  {
    headline: "Lolo Trail and the Nez Perce Crossing",
    kind: "history",
    body: `## A path older than the United States\n\nThe Lolo Trail crosses the Bitterroot Mountains southwest of Missoula, linking the Bitterroot Valley to the Clearwater River country of Idaho. Indigenous peoples — Nez Perce, Salish, and others — used it for at least several thousand years to move between summer hunting grounds on the eastern plains and winter villages on the western rivers.\n\n## Lewis and Clark, 1805 and 1806\n\nThe Lewis and Clark expedition crossed the Lolo in September 1805 and again in June 1806. The 1805 crossing nearly destroyed them — early snow, near-starvation, and the necessity of slaughtering horses to eat. The Nez Perce who fed and resupplied them in Idaho almost certainly saved the expedition. The 1806 crossing on the return trip was easier; the men were in better shape and traveled with Nez Perce guides.\n\n## 1877: the Nez Perce War\n\nA generation later, the Lolo Trail became the path of one of the most consequential events in Northern Rockies history. In 1877, Chief Joseph's band and several allied groups, refusing to be forced onto a reservation, crossed the Lolo from Idaho into Montana on their way toward Canada. They were pursued by the U.S. Army across more than 1,000 miles. The Battle of the Big Hole, fought in the Bitterroot Valley south of Missoula, was one of the war's worst days for both sides.\n\nThe Nez Perce were eventually intercepted in the Bear Paw Mountains, forty miles from Canada. Chief Joseph's surrender speech — "I will fight no more forever" — has been quoted ever since.\n\n## The trail today\n\nU.S. Highway 12 follows much of the historical route. The Lolo Pass Visitor Center marks the summit and houses interpretive exhibits about the Indigenous, exploration, and military histories of the trail. Most of the surrounding country is now National Forest, accessible to hikers and pack-trippers.`,
  },
  {
    headline: "The Garden City Nickname",
    kind: "history",
    body: `## A claim with some history behind it\n\nMissoula began calling itself "The Garden City" sometime in the 1880s. The label survives on water towers, taproom names, and city signage, and it traces back to a real agricultural moment in the city's history.\n\n## Bitterroot apples and irrigation\n\nThrough the late 19th and early 20th centuries, the Bitterroot and Missoula valleys became significant fruit-growing regions. McIntosh, Wealthy, and Wagener apples shipped east from packing houses around Florence, Stevensville, and Hamilton. Cherry, plum, and pear orchards lined the south end of Missoula. The Big Ditch irrigation project, completed in 1907, watered roughly 25,000 acres of the Bitterroot Valley and converted dry bench land into orchards almost overnight.\n\nThe Garden City label was a marketing slogan as much as a description — a way for the railroad and the early Chamber of Commerce to attract settlers and investors. It worked. Whole subdivisions of Missoula in the 1900s and 1910s were marketed to fruit-growing aspirants.\n\n## The boom went bust\n\nThe Bitterroot apple boom collapsed by the 1920s. A combination of pests, a couple of brutal winters, the rise of Washington's Wenatchee Valley as a larger apple producer, and the difficulty of long-distance shipping ended the commercial fruit economy. Many of the speculative orchards were abandoned within a decade of being planted.\n\n## What remains\n\nIndividual orchards still survive — a few commercial operations, plenty of backyard trees, the Missoula Community Orchard at the north end of town, the Western Cider operation that uses regional apples. The Garden City nickname kept going long after the orchards left. It now refers more to Missoula's reputation for tree-lined streets, dense gardens, and a community deeply attached to its public green spaces than to any particular apple. Visitors who arrive in summer often understand why.`,
  },
  {
    headline: "How Missoula Became a Refugee Resettlement City",
    kind: "history",
    body: `## A surprising role for a small western city\n\nMissoula has resettled refugees from many of the conflicts of the post-Cold War era. The city's role as a designated U.S. resettlement site began in the 1970s with Vietnamese and Hmong arrivals; it accelerated in the 1990s with families from Bosnia and Eritrea; and it expanded again starting in 2016 with arrivals from Syria, Iraq, the Democratic Republic of the Congo, and Afghanistan.\n\n## How it works\n\nResettlement is handled by Soft Landing Missoula, a nonprofit working with the International Rescue Committee and the federal Department of State. Arriving families are housed, helped with paperwork and language services, connected with employers and schools, and supported through the difficult first year. The model relies heavily on volunteer hosts and local partnerships.\n\n## A national debate, a local response\n\nIn 2016 the Missoula resettlement program briefly became a flashpoint in a national political debate over refugee admissions. Public meetings drew hundreds of supporters and a smaller number of vocal opponents. The City Council and Mayor John Engen issued public statements affirming the program; the resettlement work continued.\n\n## What's visible today\n\nMissoula's refugee community is small in absolute numbers — a few hundred families across the program's history — but their presence has reshaped parts of the city. The grocery shelves at Albertsons and Orange Street Food Farm now stock injera, halal meats, Bosnian coffee, and Syrian olives. Hellgate High School and Big Sky High School are more linguistically diverse than they were a generation ago. Refugee-owned restaurants and businesses dot the strip malls along Brooks and Reserve. For a small city far from the coasts, Missoula is unusually connected to the rest of the world, and most of that connection runs through families who chose to live here when they could have lived anywhere they were allowed.`,
  },
  {
    headline: "The Pattee Canyon and the Forest at the City's Edge",
    kind: "history",
    body: `## A neighborhood inside a forest\n\nPattee Canyon, on the southeast edge of Missoula, is one of the only American neighborhoods where you can step out of a residential street and into a working national forest. The Pattee Canyon Recreation Area, managed by the Lolo National Forest, sits at the top of the canyon and is one of the most heavily used trail systems in western Montana.\n\n## Logging, then recreation\n\nThe canyon was logged heavily in the early 20th century to supply Missoula's mills and the Anaconda Company's mines. By the 1930s, with the easiest timber cut and the Forest Service taking a more conservation-oriented approach, the canyon shifted toward recreation. The Civilian Conservation Corps built the first formal trails and the picnic area still in use today.\n\n## A trail system that anchors a neighborhood\n\nPattee Canyon contains roughly thirty miles of formal trails plus a dense web of unofficial connectors. Cross-country skiers groom several loops each winter; mountain bikers use the lower trails year-round; trail runners use the system as their training ground. The Lolo National Forest's proximity is why Missoula consistently ranks high in surveys of cities with easy outdoor access. A serious trail-runner can leave a downtown office at noon, run a four-mile loop in Pattee, and be back at a desk by 1:30.\n\n## Fire and the future\n\nThe canyon's dense conifer stands make it a real wildfire risk. Fuel reduction work, prescribed burns, and brush clearing have been ongoing for two decades, partly to protect the neighborhood that has grown up around the forest. Climate change has lengthened fire seasons; recent summers have closed parts of Pattee for weeks at a time. The forest at the city's edge is part of what makes Missoula distinctive — and part of what the city will have to actively protect to keep.`,
  },
  {
    headline: "Missoula's Brewing Tradition",
    kind: "history",
    body: `## A beer town with old roots\n\nMissoula's brewing scene is among the densest per capita in the United States, but it is not a recent invention. The Garden City Brewery operated downtown from 1881 to Prohibition. The Highlander Brewing Company brewed in town from 1933 (immediately after Repeal) until 1964. For roughly eighty years there was always at least one commercial brewery in Missoula, and for much of that period there were several.\n\n## A long dry spell, then a revival\n\nFrom 1964 to 1995, Missoula had no commercial brewery. The change came in 1995 when Bayern Brewing, founded by Bavarian-trained brewer Jürgen Knöller, opened in a former rail building on the north side. Bayern was followed by Big Sky Brewing in 1995 (now in a purpose-built facility off Hwy 93), Kettlehouse in 1996, Tamarack in 2007, Draught Works in 2011, Imagine Nation in 2014, and many more since.\n\n## A different kind of craft economy\n\nMontana's beer laws — a unique three-pint tap room cap and an 8 p.m. closing requirement for breweries without restaurants — have created a brewery culture distinct from Portland or Denver. Missoula's tap rooms are explicitly social spaces: short visits, lots of families, an early evening crowd. The taproom on Hickory Street at Kettlehouse and the riverfront patio at Imagine Nation have become casual community gathering places in a way that bars usually are not.\n\n## The festival\n\nThe Garden City Brewfest, held every May at Caras Park, brings together most of the Montana craft scene and has been an unofficial start of Missoula summer for two decades. Knöller's Bayern has been a fixture; so has the volunteer-driven Missoula Brewers' Association. For a city of seventy thousand people, the depth of brewing knowledge and the casual sophistication of the average drinker are both unusual — and both rooted in a tradition that runs back to 1881.`,
  },
];
