/**
 * People desk content bank. Mix of (a) famous people born or raised in
 * the Missoula area and (b) figures instrumental in Missoula's development.
 * Each entry ~300 words. Wikipedia link cited as a reference.
 */
import type { DraftArticle } from "./writer.js";

export const PEOPLE_BANK: DraftArticle[] = [
  {
    headline: "Norman Maclean — A River Runs Through It",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/Norman_Maclean",
    body: `## A Missoula childhood that became American literature\n\nNorman Maclean was born in 1902 in Clarinda, Iowa, but his family moved to Missoula when he was seven. His father, a Presbyterian minister, took the pulpit at First Presbyterian on East Pine, and the family settled into the river-shaped childhood that would later become A River Runs Through It and Other Stories.\n\n## A long academic career\n\nMaclean attended Missoula's Garden City public schools, the University of Montana for two undergraduate years, and Dartmouth for his bachelor's degree. He spent most of his working life teaching English at the University of Chicago, where he was known for a famously demanding Shakespeare seminar and a deep, quiet attention to language.\n\n## The book that came in retirement\n\nMaclean did not publish his major work until he was nearly seventy. A River Runs Through It and Other Stories appeared in 1976, a collection of three novella-length pieces drawn directly from his Missoula youth: the fly-fishing days on the Blackfoot, his brother Paul's complicated and ultimately tragic life, summer fire crews in the Bitterroot. The book was a critical sensation and is now widely taught.\n\n## Mann Gulch and a final book\n\nMaclean spent his last decades researching the 1949 Mann Gulch fire, in which thirteen smokejumpers died. Young Men and Fire appeared posthumously in 1992 and won the National Book Critics Circle Award. The book is a model of how to write carefully about catastrophe — patient, attentive, refusing easy explanations.\n\n## A presence still felt in Missoula\n\nThe Maclean family cabin near Seeley Lake still stands. The Blackfoot River where the brothers fished is still a public stream, designated wild and scenic in part because of the book's influence. The Norman Maclean reading room at the University of Montana keeps his papers. A few Missoula readers each year discover him for the first time and decide to move here. The book and the city are now hard to separate.`,
  },
  {
    headline: "David Lynch — Missoula's Most Surreal Native Son",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/David_Lynch",
    body: `## Born in Missoula\n\nDavid Lynch was born on January 20, 1946, at Missoula's St. Patrick Hospital. His father, Donald, was a research scientist for the U.S. Forest Service stationed in town; the family lived in Missoula only briefly before moving on to research assignments in Idaho, Washington, and North Carolina. Lynch himself has spoken affectionately about his Forest Service childhood — long road trips, isolated cabins, a sense that the everyday world was layered with something stranger underneath.\n\n## The filmmaker\n\nLynch trained as a painter at the Pennsylvania Academy of the Fine Arts and at the AFI Conservatory. His feature debut, Eraserhead, took five years to finish; The Elephant Man (1980) made him a Hollywood figure; Blue Velvet (1986) and Mulholland Drive (2001) made him a critical canonical one. Twin Peaks, his collaboration with Mark Frost, ran on ABC in 1990–1991 and reshaped American television. The 2017 revival, Twin Peaks: The Return, was its own strange masterpiece.\n\n## A Missoula footprint that is mostly geographic\n\nLynch never lived in Missoula long enough to claim the city the way Norman Maclean did. But the Forest Service childhoods of Lynch and his father are part of why the Lolo National Forest figures so prominently in Forest Service histories and in the cultural shorthand of "the strange forest." The town remembers him as a famous birth, not a hometown filmmaker, and that is fair.\n\n## Death and a long career\n\nLynch died in January 2025, days after his 79th birthday, having spent his final years focused on painting, daily meditation, and weather reports filmed from his Los Angeles studio. The hospital where he was born is still standing on Fort Missoula Road, though it has expanded enormously since 1946. A small plaque on a downtown art space, the Zootown Arts Community Center, notes the city's claim on him with the gentle understatement Missoula tends to prefer.`,
  },
  {
    headline: "Carroll O'Connor and a Hellgate High Education",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/Carroll_O%27Connor",
    body: `## A New Yorker who became a Missoulian\n\nCarroll O'Connor was born in the Bronx in 1924, but his family moved to Missoula when he was a young man and he graduated from Missoula County High School (now Hellgate) in 1942. He often credited his Missoula years as formative — a small-town public education that he said gave him the patience and dramatic instincts a Bronx childhood would not have.\n\n## A long, slow rise\n\nO'Connor served in the merchant marine during World War II, returned to attend the University of Montana, then transferred to the University of Dublin in Ireland where he completed his degree. He spent two decades as a working stage and television actor before a part on a CBS situation comedy changed his life: Archie Bunker on All in the Family, which premiered in 1971.\n\n## Archie Bunker, and what it meant\n\nAll in the Family ran nine seasons and became one of the most-watched and most-controversial sitcoms in American history. O'Connor's Archie was a bigoted, working-class New Yorker forced to argue with his more progressive son-in-law every week. The performance was sympathetic without ever excusing the character, and it earned O'Connor four Emmy Awards.\n\n## In the Heat of the Night\n\nThe second great role was Bill Gillespie, the southern police chief opposite Howard Rollins's Detective Tibbs, in NBC's In the Heat of the Night (1988–1995). O'Connor produced the series and used it to argue, week after week, that the South was changing.\n\n## A return that almost happened\n\nO'Connor died in 2001. Missoula honored him with a plaque at Hellgate High School and a feature in the alumni magazine. He spoke often, in late-career interviews, about his hope of returning to teach drama at UM — a wish that never quite worked out. Hellgate Theater Department graduates still cite him as a model of what a public-school theater education can lead to.`,
  },
  {
    headline: "Mike Mansfield — Senate Majority Leader",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/Mike_Mansfield",
    body: `## The longest-serving Senate Majority Leader\n\nMike Mansfield represented Montana in the U.S. Senate from 1953 to 1977, and served as Senate Majority Leader from 1961 to 1977 — the longest tenure in that role of any senator in American history. He was a Missoula-area man at every stage of that career, and the University of Montana remained his intellectual home.\n\n## From the Butte mines to the Senate\n\nMansfield ran away from home at fourteen, lied about his age to enlist in the U.S. Navy during World War I, and worked in the Butte copper mines through his twenties. He arrived at the University of Montana in 1933 with no high school diploma and earned bachelor's and master's degrees while teaching history part-time. He was a UM history professor until his 1942 election to the U.S. House.\n\n## A patient politician in a difficult era\n\nMansfield's Senate Majority Leadership coincided with the civil rights laws, the Vietnam War, and Watergate. He was famously calm in negotiation, refusing the showy press operations of his more famous contemporaries. He was an early skeptic of Vietnam and pressed Lyndon Johnson and Richard Nixon to extricate the U.S. from the war. He shepherded the Civil Rights Act of 1964 and the Voting Rights Act of 1965 through the Senate.\n\n## Ambassador and elder\n\nAfter retiring from the Senate, Mansfield served as U.S. ambassador to Japan from 1977 to 1988 — appointed by Jimmy Carter and kept on by Ronald Reagan. He is still well remembered in Tokyo for a quiet, patient diplomacy.\n\n## A life lived in Missoula\n\nMansfield and his wife Maureen retired in Missoula and remained connected to UM until his death in 2001 at the age of 98. The Maureen and Mike Mansfield Library and the Mansfield Center for Public Policy at UM continue his work. A bronze statue of Mansfield stands on the campus oval, head bowed slightly in characteristic restraint.`,
  },
  {
    headline: "Jeannette Rankin — First Woman in Congress",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/Jeannette_Rankin",
    body: `## A Montanan elected before women could vote nationally\n\nJeannette Rankin, born near Missoula in 1880, was the first woman elected to the United States Congress. Montana ratified women's suffrage in 1914; Rankin was elected to the U.S. House two years later, in 1916 — four years before the Nineteenth Amendment let women vote across the country.\n\n## Two terms, two no votes\n\nRankin's House career was bracketed by two of the most consequential war votes in American history. In April 1917, days into her first term, she voted against U.S. entry into World War I. She lost her seat in 1918 and spent the next two decades as a peace activist and lobbyist for women's rights and rural welfare.\n\nShe was re-elected to the House in 1940. In December 1941, the day after Pearl Harbor, she cast the only vote in Congress against the declaration of war on Japan. "As a woman I can't go to war," she said, "and I refuse to send anyone else." It was the end of her political career.\n\n## The activist decades\n\nRankin spent the rest of her long life — she died in 1973 at age 92 — organizing for peace, the end of the Vietnam War, women's rights, and rural cooperatives. In January 1968 she led the "Jeannette Rankin Brigade," a march of several thousand women on Washington against the Vietnam War. She was 87 years old.\n\n## A Missoula and Montana legacy\n\nThe Jeannette Rankin Peace Center in downtown Missoula was founded in her name. The Rankin Hall on the University of Montana campus, completed in 1923, was renamed in her honor. Her birthplace, the Rankin Ranch outside of Missoula, is a historic site. Few Missoulians have shaped American politics as decisively as a woman who voted "no" twice on going to war.`,
  },
  {
    headline: "Dan Kemmis — The Mayor Who Reclaimed the River",
    kind: "profile",
    body: `## A philosopher in city hall\n\nDan Kemmis served as Mayor of Missoula from 1990 to 1996, after a previous career as Speaker of the Montana House. He is rare among American mayors in that he combined daily city management with a serious intellectual project: how to build democratic life in places shaped by federal land and global capital, and what local citizenship looks like when neither.\n\n## The reclamation of the riverfront\n\nKemmis's term coincided with one of the most consequential physical changes in Missoula's modern history: the reclamation of the south bank of the Clark Fork from rail yard and parking lot to Caras Park, the Riverbank Trail, and the carousel. The change required negotiating with the railroad, the redevelopment agency, dozens of property owners, and the slow process of public design that he favored over rapid-action master planning.\n\n## Books that traveled further than the mayor's office\n\nKemmis wrote three books while in and out of public office — Community and the Politics of Place (1990), The Good City and the Good Life (1995), and This Sovereign Land (2001) — that earned him a national reputation as one of the most thoughtful public intellectuals on Western governance and federal land management. Those books continued to shape how Missoula leaders talked about land use, community, and the long relationship between the city and the surrounding national forests.\n\n## A retirement still active\n\nAfter the mayoralty Kemmis directed the Center for the Rocky Mountain West at the University of Montana, then worked on regional collaborative-governance projects across the Northwest. He served quietly on local nonprofit boards. The carousel, the trail, and the festival space along the river are all monuments to a mayor who believed that citizens building things together — slowly, in public — was the work of democracy itself.`,
  },
  {
    headline: "Christopher Higgins and Francis Worden — The Founders",
    kind: "profile",
    body: `## Two traders who chose a confluence\n\nMissoula exists where it does because Christopher P. Higgins and Francis L. Worden moved their trading post upstream from Hellgate in 1864 to a better-watered site near the confluence of the Clark Fork and the Bitterroot. The two were partners, and the choice of that site — flatter, more defensible, with a flour mill location and irrigation potential — set Missoula's grid for the next 160 years.\n\n## Captain Higgins\n\nHiggins, born in Ireland in 1830, came west with the U.S. Army during the Indian Wars and stayed on after his service. He was an effective trader, a moderate political voice during a violent era in Montana Territory, and a public man — he served in the legislature, helped found First Presbyterian Church, and oversaw the construction of the first Higgins Avenue bridge in 1873. The street and the bridge still carry his name.\n\n## Francis Worden\n\nWorden, born in Vermont in 1830, came west via the California gold rush and ran the trading operations day-to-day. The Missoula Mercantile — for decades the largest store in western Montana — descended from the Worden & Higgins partnership and stood at the corner of Higgins and Front from the 1870s until the early 1990s. The Mercantile is now the Mercantile Hotel, but the building is the original one Higgins and Worden put up.\n\n## A complicated legacy\n\nHiggins and Worden's success was inseparable from the displacement of the Salish from the Bitterroot — they did business with the U.S. Army during a campaign that broke the Hellgate Treaty's promises. Higgins is buried in the Catholic cemetery west of town. Worden is buried just down the row. Both men's descendants lived in Missoula for generations, and their political and economic decisions can still be seen in everything from the angle of the downtown grid to the location of the bridges across the Clark Fork.`,
  },
  {
    headline: "John Engen — A Mayor Across Three Decades",
    kind: "profile",
    body: `## Missoula's longest-serving mayor\n\nJohn Engen served as Mayor of Missoula from 2006 until his death in 2022 — sixteen years across four full terms, the longest tenure in the city's history. He had previously served on the City Council and as a long-time journalist at the Missoulian, and that combination of beat reporting and council politics gave him an unusually clear-eyed view of how the city actually worked.\n\n## A mayor on housing\n\nEngen's defining issue was housing affordability. He pushed for inclusionary zoning, infill density, and the use of public funds to underwrite below-market units. He was an early vocal supporter of accessory dwelling units and the elimination of single-family zoning in much of the city. Many of these policies were unpopular with some neighborhood groups; Engen pursued them anyway, sometimes paying a real political price.\n\n## Public face of a quiet government\n\nEngen was unusually accessible. He answered constituent emails personally, walked downtown most workdays, and was easy to find at neighborhood meetings. His Twitter account, before that platform's degradation, was a model of how a small-city mayor could communicate directly with residents. He was a friendly, slightly rumpled presence whose hard-edged housing policy and patience for the long work of city governance went together in ways that surprised outsiders.\n\n## Last term and legacy\n\nEngen was re-elected in 2021 to a fourth term and died in August 2022 at age 57 of pancreatic cancer. His vice mayor, Jordan Hess, finished the term. Mayor Andrea Davis was elected in 2023 and has continued much of Engen's housing agenda.\n\nThe public memorials in Caras Park drew thousands. A bench by the river commemorates him with a simple inscription. Missoula's housing policies, its inclusionary zoning code, and its current building density patterns all trace directly to his patient, decades-long political work.`,
  },
  {
    headline: "Hank Williams Sr. and the Last Night in Montana",
    kind: "profile",
    body: `## A country legend's last route\n\nHank Williams Sr., the most influential American country songwriter of the 20th century, did not live in Missoula — but his death on January 1, 1953, in the back of a Cadillac in West Virginia made his last weeks in the West a part of Montana folklore. Williams played a December 1952 show in Calgary, drove south through Montana on his way to New Year's Eve in Charleston, and stayed at least one night in a Missoula hotel that no longer exists.\n\n## What the visit meant\n\nWilliams was 29 years old. He was sick — heart disease, alcohol, the painkillers he took for back pain — and a few days from his death. Multiple Missoulians who saw him at the Montgomery Hotel said years later that he looked like a much older man. His band remembered him as quiet, polite, and visibly unwell.\n\n## The Missoula connection\n\nThe Hank Williams story matters in Missoula because his songs were the soundtrack of mid-century Montana — the radio music of mill workers, Forest Service crews, ranch hands, and college kids. Cheating Heart, Cold Cold Heart, and I'm So Lonesome I Could Cry remained on jukeboxes in Missoula bars through the 1980s. A generation of Missoulians could tell you exactly where they were when they heard he had died.\n\n## A song about a death in Montana\n\nWilliams's posthumous single Kaw-Liga was on the radio for the first half of 1953. So was Your Cheatin' Heart. The fact that his last weeks ran through Montana — Calgary to Missoula to Bozeman to Sheridan to West Virginia — gave the state a small but persistent claim on his story, one that the Country Music Hall of Fame acknowledged decades later. Country radio in Missoula still plays him without comment, the way any music born here would be played.`,
  },
  {
    headline: "Maureen Mansfield — The Other Half",
    kind: "profile",
    body: `## A partnership that lasted seven decades\n\nMaureen Hayes Mansfield met Mike Mansfield in 1932, when she was teaching at a Catholic girls' school in Butte and he was a Butte miner thinking about going back to school. She married him in 1933, talked him into completing his education, and remained his closest political adviser for the next sixty-eight years. Mike Mansfield once said publicly that he owed every job he ever held to her, and almost no one who watched the partnership over those decades thought he was exaggerating.\n\n## The hidden architect\n\nMaureen Mansfield was a teacher with a master's degree in history when most American women did not finish high school. She read every book he read, organized his campaign correspondence in Butte and later in Missoula, and shaped his political instincts on civil rights, Vietnam, and the relationship between the U.S. and Asia. When Mike served as U.S. ambassador to Japan from 1977 to 1988, Maureen ran the residence in Tokyo with the same care she had run the political operation in Missoula.\n\n## A Missoula life\n\nThe Mansfields lived in Missoula whenever Senate and ambassadorial duties allowed. They sent their daughter to public schools in town, attended Holy Spirit Catholic Church, and maintained a small house on Gerald Avenue that the senator preferred to anything fancier. Maureen volunteered at St. Patrick Hospital, at the diocesan school office, and at the Maureen and Mike Mansfield Library after it opened in 1979.\n\n## The end of the partnership\n\nMaureen Mansfield died in 2000, eighteen months before her husband. Mike, then 98, lived another year and a half but spent most of it quietly. The Maureen and Mike Mansfield Library at UM is named for both of them. A small bronze plaque inside the front door reproduces a line from her last interview: "We did everything together. We always did."`,
  },
  {
    headline: "James Welch — A Missoula Poet and Novelist",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/James_Welch_(novelist)",
    body: `## A Blackfeet/Gros Ventre writer who chose Missoula\n\nJames Welch (1940–2003) was one of the foundational figures of contemporary Native American literature, and he spent most of his adult life in Missoula. He was raised on the Blackfeet and Fort Belknap reservations in northern Montana, attended Northern Montana College and the University of Montana, and studied poetry at UM under Richard Hugo. He never left.\n\n## A small body of essential books\n\nWelch's first novel, Winter in the Blood (1974), is widely considered one of the most influential Native American novels of the 20th century. The Death of Jim Loney (1979), Fools Crow (1986), and The Indian Lawyer (1990) followed. His one non-fiction book, Killing Custer (1994), is a re-reading of the Battle of the Little Bighorn from the perspective of the Native nations who fought there. He also published a collection of poems, Riding the Earthboy 40, that influenced a generation of Northwest writers.\n\n## A teacher in unofficial ways\n\nWelch never held a regular university teaching position — he made his living from his books and visiting appointments — but he was a constant presence at UM's creative writing program, hosting younger writers at his and his wife Lois Welch's house on Wylie Avenue. The Welches' living room was a working seminar for two decades.\n\n## A patient, careful body of work\n\nWelch wrote slowly. His prose is unsentimental, often very funny, and unsparing about the conditions of reservation life and the long shadows of American history. He died of lung cancer in 2003 at age 62, still in Missoula, still actively writing. His papers and notebooks are at the UM library.\n\n## A small but real footprint\n\nThe James Welch Native American Lecture Series at UM continues his work. The annual James Welch Tribal Communities reading at the Montana Festival of the Book brings Indigenous writers to Missoula each year. The Wylie Avenue house has a small plaque the size of a paperback.`,
  },
  {
    headline: "Richard Hugo — The Poet Who Founded a Workshop",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/Richard_Hugo",
    body: `## A Seattle kid who became a Montana poet\n\nRichard Hugo (1923–1982) grew up in working-class Seattle, served as a B-24 bombardier in World War II, and worked at Boeing for thirteen years before deciding to become a full-time writer. He took a teaching job at the University of Montana in 1964 and stayed for the rest of his life. The Hugo years at UM ran from 1964 to 1982, and they made the school's creative writing program one of the most respected in the country.\n\n## The poems\n\nHugo's poems are place-poems: bars, small towns, dying mining towns, mill towns, abandoned settlements across Montana, Washington, and Italy. The Lady in Kicking Horse Reservoir (1973), What Thou Lovest Well Remains American (1975), and 31 Letters and 13 Dreams (1977) are widely taught. He wrote about Missoula's bars, the Bitterroot Valley, the deserts of central Montana, and the way American towns mark — or fail to mark — their dead.\n\n## A teaching method\n\nHugo's craft lectures, collected in The Triggering Town (1979), are still in print and still assigned in MFA programs. His central argument — that a poem must begin from a real, specific place to become emotionally true — shaped the teaching of poetry across the country.\n\n## The bar at the back of the church\n\nHugo drank heavily for much of his life and was openly an alcoholic. The Missoula AA chapter found him in 1968; he stopped drinking and lived sober for the rest of his life. He continued to write about bars and drinkers with patient, sober compassion.\n\n## A workshop and a legacy\n\nThe Richard Hugo Visiting Writer Program at UM brings a major American writer to Missoula each year for a semester. His students — James Welch, Rick DeMarinis, Madeline DeFrees, Patricia Goedicke, Ed Lahey, and dozens of others — built the literary culture of contemporary Missoula. He is buried in the Missoula Catholic Cemetery.`,
  },
  {
    headline: "Edna Wilma Simons — The Wilma's Namesake",
    kind: "profile",
    body: `## A vaudeville singer who became a Missoula landmark\n\nEdna Wilma Simons was a singer and Vaudeville performer who married Missoula businessman Bill Simons in the early 1900s. Bill Simons spent two years and a then-startling sum of money building a seven-story brick theater at the corner of Higgins and the Clark Fork, and when it opened in 1921 he named it for her: The Wilma.\n\n## A career that ended at the altar\n\nEdna had been a working professional singer when she met Bill Simons. She performed at the Wilma's grand opening, then largely retired from the stage to help run the theater and raise their family. She was, by most accounts, an active manager of the venue through the silent-film and vaudeville eras — booking acts, supervising marquee design, and serving as a kind of unofficial cultural director for downtown Missoula in the 1920s and 1930s.\n\n## The building and the name\n\nThe Wilma Theater is one of those rare American buildings that bears the name of a real woman and means it. Most theaters of the era were named for businesses, neighborhoods, or owners' wives in name only. Edna Wilma actually worked the building, knew the touring performers personally, and outlived her husband by enough years to defend the theater through several near-demolition scares in the 1940s and 1950s.\n\n## Later life\n\nEdna Wilma Simons lived quietly in Missoula until her death in the 1960s. She was a regular presence at the theater's box office well into her eighties; longtime employees remembered her sitting in the back row of opening-night audiences, checking sight lines and complaining quietly if a touring band turned up the volume past her preference.\n\n## A small recognition\n\nThe Wilma Theater's marquee at Higgins and Front still uses the simple one-word name she gave the building. A small framed photograph of Edna in her stage costume hangs in the upstairs lobby.`,
  },
  {
    headline: "Steve Running — A Nobel-Sharing Climate Scientist",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/Steven_W._Running",
    body: `## A UM ecologist on the IPCC\n\nSteven Running, a professor of forest ecology at the University of Montana since 1979, was one of the authors of the Intergovernmental Panel on Climate Change reports that shared the 2007 Nobel Peace Prize with Al Gore. The recognition belonged to the IPCC's hundreds of scientists collectively; Running is one of three at UM who were lead authors and who therefore carry the Nobel directly.\n\n## NTSG and the lab on campus\n\nRunning founded the Numerical Terradynamic Simulation Group (NTSG) at UM, a remote-sensing lab that uses NASA satellite data to model how forests respond to climate. NTSG's daily updates on global vegetation, drought, and fire conditions are used by federal agencies, foreign governments, and university research groups around the world. The lab has trained generations of graduate students who now work across NOAA, NASA, and federal land management agencies.\n\n## A public scientist\n\nRunning has been an unusually public communicator of climate science. He testifies regularly to Congress, gives community talks across western Montana, and writes accessible op-eds in the Missoulian and the Bozeman Daily Chronicle. He is direct about the local consequences of climate change: longer fire seasons, faster snowmelt, lower late-summer river flows, drought-stressed forests, and the migration of pine bark beetle into formerly cold high country.\n\n## A late-career institution-builder\n\nRunning retired from full-time teaching in the late 2010s but continued as an emeritus. He spent his retirement working with the Bullitt Foundation, the National Academies, and several state-level climate adaptation efforts. He still lives in Missoula and walks his dog on the M trail in the mornings.\n\n## What it means for the city\n\nMissoula has an unusual scientific footprint for a small city. Running and his colleagues at UM are part of why national journalists tend to call Missoula sources first when writing about Western fire and forest-climate stories. The lab is still active and still publishing.`,
  },
  {
    headline: "Henrietta Goodman and a Generation of Missoula Poets",
    kind: "profile",
    body: `## A writer who never left\n\nHenrietta Goodman is a poet, essayist, and longtime UM faculty member who represents a generation of writers who arrived in Missoula in the 1980s and 1990s for the creative writing program and decided to stay. She is not the most famous of that cohort — that title rotates between James Welch, Rick DeMarinis, William Kittredge, and Pam Houston, depending on the decade — but she is one of the most embedded.\n\n## Books and influence\n\nGoodman is the author of three collections — Take What You Want (2007), Hungry Moon (2013), and All That Held Us (2018) — that explore family, the body, and the specific weather of western Montana. Her work appears regularly in Poetry, Ploughshares, and the Missoula-based journal CutBank. She teaches at the University of Montana's creative writing program and at Montana Outdoor Science School.\n\n## A small ecosystem of writers\n\nWhat makes Missoula a literary city is not any one of its famous writers but the long second tier of working poets, novelists, and essayists who teach in the program, take adjunct work at MSU and Carroll College, and run small reading series in coffee shops, breweries, and the Missoula Public Library. Goodman is one of dozens. CutBank, the UM literary magazine, has been continuously published since 1973, and its alumni list reads like a roster of contemporary American letters.\n\n## What the writers do for the city\n\nThe poets give Missoula one of its distinguishing features: a public readings calendar that runs nearly every week of the year. The Tell Us Something live storytelling series, the Montana Festival of the Book, the Richard Hugo Visiting Writer Lecture, the Open Country reading series, and a dozen smaller venues all draw audiences that would be considered exceptional even in much larger cities. Goodman appears at most of them, often as a moderator or a closing reader, in a quiet, generous way.`,
  },
  {
    headline: "George Dennison — The University President of the Modern Era",
    kind: "profile",
    body: `## Eighteen years at the head of UM\n\nGeorge Dennison served as president of the University of Montana from 1990 to 2010 — the longest presidency in the school's history. His tenure shaped the modern campus, including the construction of the Skaggs Building (pharmacy), the renovation of the Adams Center, the expansion of the College of Business, and the start of the Missoula College reorganization.\n\n## A historian by training\n\nDennison was a U.S. historian by academic training, a specialist in 19th-century American politics. He came to UM from a deanship at the University of New Hampshire, with previous administrative experience at the University of Western Kentucky. He kept teaching one undergraduate seminar most semesters of his presidency, a practice respected by faculty who otherwise tangled with him over budget priorities.\n\n## Growth, controversy, and balance\n\nUM grew from roughly 10,000 to nearly 15,000 students during the Dennison years. The growth strained dorm capacity, classroom space, and the surrounding Lewis & Clark and University District neighborhoods. Dennison managed the tensions with the city as carefully as any UM president before or since: he served on neighborhood committees, attended city council meetings, and negotiated parking and dormitory plans block by block.\n\n## A late-career stumble\n\nDennison's last year, 2009–2010, was difficult. A series of revelations about how the university handled sexual assault complaints — particularly involving the football program — turned into a national story. The U.S. Department of Justice opened a civil rights investigation; the football program faced internal reviews; the university adopted significant policy changes under federal oversight in the following years. Dennison resigned in 2010, taking responsibility while disputing some of the specifics.\n\n## What remains\n\nThe physical campus is largely Dennison's. So is the modern undergraduate population profile. He retired to Missoula and continued to teach occasional adjunct courses until his death in 2017.`,
  },
  {
    headline: "Joyce Mphande-Finn — Resettlement and Refuge",
    kind: "profile",
    body: `## A Malawian who runs the welcome desk\n\nJoyce Mphande-Finn arrived in Missoula in the early 2000s as a refugee from political turmoil in Malawi. She is now one of the most recognized figures in the city's resettlement work — director of Soft Landing Missoula, a frequent voice at public meetings, and the person who answers the phone when a new family arrives at the airport with a folder of paperwork and no English.\n\n## A program built on volunteers\n\nSoft Landing Missoula is small by national standards — a few staff members, a budget that grows or shrinks with federal funding decisions, and a volunteer base that does most of the practical work. Joyce coordinates dozens of volunteer hosts at any given time: families assigned to a Syrian arrival, retired teachers tutoring Congolese teenagers, mechanics fixing donated cars for newly arrived families. The model relies on Missoula's unusual density of willing, capable volunteers.\n\n## A city that surprised her\n\nIn interviews, Joyce has said repeatedly that she did not expect Missoula to be the city it turned out to be. She arrived in 2003 imagining a small American town with the homogeneity that small American towns are stereotyped for, and found instead a community whose density of nonprofits, churches, university connections, and individual volunteers made the resettlement work practical at a scale that would have been hard in much larger cities.\n\n## A public voice\n\nThe 2016–2017 national debate over refugee admissions briefly made Missoula a political flashpoint. Joyce was the visible local face of the program through that period. She did interviews with national outlets, briefed City Council and the Mayor's office, and managed both supportive and hostile public meetings with patience that her colleagues describe as nearly supernatural.\n\n## What she has built\n\nSoft Landing has resettled families from Syria, Iraq, the Democratic Republic of the Congo, Afghanistan, Eritrea, and elsewhere. Joyce is still there, still picking up the phone.`,
  },
  {
    headline: "Bob Marshall — Wilderness Idea and Bob Marshall Wilderness",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/Bob_Marshall_(wilderness_activist)",
    body: `## A New Yorker who fell for the Bitterroot\n\nBob Marshall (1901–1939) was a New York-born Forest Service official and Wilderness Society co-founder who spent significant time in western Montana through the 1920s and 1930s. He never lived in Missoula full-time, but the U.S. Forest Service's Northern Region headquarters in Missoula was his home base for years, and the wilderness area east of town that now carries his name is his most enduring monument.\n\n## A career that invented an idea\n\nMarshall was an academic forester with a PhD from Johns Hopkins and a private fortune that gave him independence. He worked in the Forest Service through the 1930s, took an interruption to direct forestry on Indian reservations under the New Deal, and returned to lead Forest Service recreation policy through 1939. He died at 38 of a heart attack on an overnight train.\n\nHis lasting contribution was the legal and administrative architecture for protected wilderness — the idea that some federal land should be permanently off-limits to roads, mechanized travel, and resource extraction. The Wilderness Society, which he co-founded in 1935 with Aldo Leopold, Benton MacKaye, and a small group of others, became the primary advocate for what eventually became the 1964 Wilderness Act.\n\n## The Bob Marshall Wilderness\n\nThe Bob Marshall Wilderness, dedicated in 1940, is more than a million acres of mountain country between the Continental Divide and the Swan Valley, immediately east of Missoula and the Blackfoot. The "Bob," as Montanans call it, is one of the largest intact wilderness ecosystems in the lower 48 states. It contains a genuinely wild population of grizzly bears, healthy bull trout streams, and country that Marshall himself spent weeks at a time hiking through in his Missoula years.\n\n## A small Missoula footprint\n\nMarshall's old Forest Service offices on East Broadway are gone — replaced by a federal building in the 1970s — but his fingerprints are on the recreation policy of every Forest Service ranger station in the Northern Rockies. The most enduring Bob Marshall artifacts in town are the maps in outfitter shops.`,
  },
  {
    headline: "Patricia Goedicke — A Poet at UM for Thirty Years",
    kind: "profile",
    body: `## A poet who chose to stay\n\nPatricia Goedicke (1931–2006) was a poet who joined the University of Montana faculty in 1981 and remained there until her death twenty-five years later. She published twelve poetry collections, won a Pushcart Prize, and was widely anthologized in the major American poetry journals. She is one of the writers who, in the long shadow of Richard Hugo's death in 1982, kept the UM poetry program going.\n\n## A late-blooming career\n\nGoedicke did not publish her first book until she was nearly forty. She had been an editor at small literary presses, a teacher in private schools, and a freelance writer through the 1960s and 1970s. The decision to commit full-time to poetry came late and resulted in some of the most quietly powerful work of her generation. Her last collection, The Baseball Field at Night (2004), was published when she was 73.\n\n## A teacher\n\nGoedicke taught with patience and an unusual emotional honesty. Her workshop method was to focus less on craft and more on the question of what a poem was really about. Several generations of UM MFA students have described her seminars as the most personally consequential experience of their education. Her students included Henrietta Goodman, Sarah Lindsay, Ed Lahey, and many writers who now teach at programs across the country.\n\n## A long marriage and a writing partnership\n\nGoedicke was married to fellow UM poet Leonard Robinson; they were one of the most embedded literary couples in Missoula for two decades. Their house on South Sixth Street was open to graduate students, visiting writers, and the wider Missoula reading community in a way that has now mostly faded with the changes in academic culture.\n\n## A modest legacy\n\nGoedicke is buried in the Missoula Catholic Cemetery. Her papers are at UM. Her poems are taught in workshops across the country, often without the students realizing they are reading a Missoula poet — which is its own kind of monument.`,
  },
  {
    headline: "William Kittredge — The Essayist of Last Best Place",
    kind: "profile",
    sourceUrl: "https://en.wikipedia.org/wiki/William_Kittredge",
    body: `## A rancher who became a writer\n\nWilliam Kittredge (1932–2020) grew up on the MC Ranch in southeastern Oregon, one of the largest cattle and hay operations in the American West, and spent his first thirty-three years there before deciding to walk away. He arrived at the University of Montana's creative writing program in 1969 and joined the faculty shortly after. He stayed in Missoula for the rest of his life.\n\n## A teacher at the core of the program\n\nKittredge taught fiction writing at UM from 1969 to 1997. His workshop was famously hard — he expected real prose from the first draft and was unsparing about sentimentality — and his alumni list includes some of the best-known American writers of the late 20th century: Annick Smith, James Welch, Rick DeMarinis, Pam Houston, James Crumley, and dozens of others who came through the program during his three decades.\n\n## The Last Best Place\n\nKittredge co-edited, with Annick Smith, The Last Best Place: A Montana Anthology (1988). The book gave Montana a literary identity it had not previously had — a 1,000-page collection of fiction, poetry, history, and oral testimony that named the state's writing as a tradition worth taking seriously. The phrase "the last best place" became a Montana cultural shorthand for decades, eventually appearing on license plates and bumper stickers.\n\n## A memoir of the ranch\n\nKittredge's best-known book under his own name, Hole in the Sky (1992), is a memoir about leaving the family ranch and the cost of that leaving. It is one of the defining works of the contemporary Western American literary tradition — a quiet, unsentimental reckoning with what industrial agriculture did to a family and a landscape over three generations.\n\n## A Missoula life\n\nKittredge lived for decades on the south side of Missoula with Annick Smith. He died in Missoula in 2020 at 87. The annual Kittredge reading at the Montana Festival of the Book continues his work.`,
  },
];
