import type { InsertStory, InsertEvent, InsertSource } from "@shared/schema";

// Anchor date for seeds — posts are scheduled relative to NOW at startup.
// We compute offsets (in minutes from now) and turn them into ISO strings at seed time.
type SeedStory = Omit<InsertStory, "publishedAt" | "fetchedAt" | "tags"> & {
  minutesAgo: number;
  tags: string[];
};

const S = (s: SeedStory): SeedStory => s;

export const SEED_STORIES: SeedStory[] = [
  // =========================
  // CITY DESK (civic / public)
  // =========================
  S({
    headline: "City Council approves updated downtown parking plan",
    summary:
      "Missoula City Council voted 9–3 to adopt revised downtown parking rates and extend metered hours on Higgins Ave. Changes take effect July 1.",
    whyItMatters:
      "Affects every downtown commuter, business owner, and visitor. New structure funds sidewalk repair and transit subsidies.",
    desk: "city",
    tags: ["city-council", "downtown", "transportation"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 42,
  }),
  S({
    headline: "Mayor Davis announces affordable housing working group",
    summary:
      "A new 11-member working group will draft recommendations on land-trust expansion and accessory dwelling incentives by September.",
    whyItMatters:
      "Missoula's median rent has climbed faster than wages since 2021. Group's output will shape 2027 budget priorities.",
    desk: "city",
    tags: ["housing", "policy", "mayor"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Missoula",
    status: "Developing",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 180,
  }),
  S({
    headline: "Public works: Brooks Street resurfacing begins Monday",
    summary:
      "Crews will resurface Brooks Street between Stephens and Russell over three weeks. Expect single-lane closures 7am–5pm weekdays.",
    desk: "city",
    tags: ["public-works", "traffic", "brooks-st"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Brooks Street",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 6,
  }),
  S({
    headline: "County Commission to hear wildfire mitigation plan Thursday",
    summary:
      "Missoula County Commissioners will review the 2026 Community Wildfire Protection Plan update at 1:30pm in the courthouse.",
    whyItMatters:
      "Plan determines defensible-space grant eligibility for homeowners in the Rattlesnake, Grant Creek, and Pattee Canyon.",
    desk: "city",
    tags: ["county", "wildfire", "public-meeting"],
    sourceName: "Missoula County",
    sourceUrl: "https://www.missoulacounty.us/",
    sourceType: "Official",
    location: "Missoula County Courthouse",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 9,
  }),
  S({
    headline: "Mountain Line adds Sunday service on Route 2",
    summary:
      "Starting May 4, Mountain Line's Route 2 between downtown and Southgate Mall will run 9am–6pm on Sundays. Service remains fare-free.",
    desk: "city",
    tags: ["transit", "mountain-line"],
    sourceName: "KPAX",
    sourceUrl: "https://www.kpax.com/",
    sourceType: "Local News",
    location: "Missoula",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 14,
  }),
  S({
    headline: "Clark Fork water quality advisory lifted",
    summary:
      "Montana DEQ lifted the temporary E. coli advisory for the Clark Fork between Kelly Island and the California Street Bridge after two consecutive clean samples.",
    desk: "city",
    tags: ["public-health", "clark-fork", "environment"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Clark Fork River",
    status: "Updated",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 20,
  }),
  S({
    headline: "Missoula Fire Department hiring nine new firefighters",
    summary:
      "MFD opened applications for nine entry-level positions funded by the 2025 public safety levy. Applications close May 12.",
    desk: "city",
    tags: ["public-safety", "hiring", "fire"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 28,
  }),
  S({
    headline: "Missoula Public Library hosts citizenship clinic Saturday",
    summary:
      "Free legal help for citizenship applications will be offered at the downtown library 10am–2pm, hosted by Soft Landing Missoula.",
    desk: "city",
    tags: ["library", "community", "immigration"],
    sourceName: "Missoula Public Library",
    sourceUrl: "https://www.missoulapubliclibrary.org/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "Event",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 36,
  }),
  S({
    headline: "City to pilot curbside composting in three neighborhoods",
    summary:
      "A six-month curbside composting pilot begins May 15 in the Rattlesnake, University District, and Lower Rattlesnake neighborhoods.",
    whyItMatters:
      "If participation tops 35%, the program may expand citywide in 2027 — a major lever on Missoula's zero-waste target.",
    desk: "city",
    tags: ["environment", "waste", "pilot"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Rattlesnake / University",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 48,
  }),
  S({
    headline: "Snow plowing season officially ends April 30",
    summary:
      "Streets division will transition from snow-and-ice operations to pothole patching and street sweeping on April 30.",
    desk: "city",
    tags: ["public-works", "streets"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 60,
  }),
  S({
    headline: "Open Space Advisory Committee seeks two new members",
    summary:
      "Applications due May 20 for two open seats on the committee that reviews trail, conservation, and park acquisition proposals.",
    desk: "city",
    tags: ["open-space", "volunteer"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 72,
  }),
  S({
    headline: "MRL-BNSF merger review reaches Montana rail commission",
    summary:
      "State rail commissioners will take public comment Wednesday on service commitments tied to the finalized MRL-BNSF consolidation.",
    desk: "city",
    tags: ["transportation", "rail", "state"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Missoula",
    status: "Developing",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 96,
  }),
  S({
    headline: "New crosswalk signal activated at 5th & Higgins",
    summary:
      "A pedestrian-activated HAWK signal went live Monday at 5th and Higgins after two years of neighborhood advocacy.",
    desk: "city",
    tags: ["safety", "pedestrian", "downtown"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 120,
  }),
  S({
    headline: "Public comment opens on Scott Street sub-area plan",
    summary:
      "City planning opened a 30-day public comment window on the Scott Street redevelopment framework covering 180 acres north of the river.",
    whyItMatters:
      "Plan shapes housing density, transit connections, and riverfront access for one of Missoula's largest remaining infill zones.",
    desk: "city",
    tags: ["planning", "scott-street", "housing"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Northside",
    status: "New",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 168,
  }),
  S({
    headline: "Missoula County sheriff's office releases Q1 call data",
    summary:
      "Total calls for service rose 4.2% year-over-year; traffic stops declined 9%. Full dashboard now public on the county portal.",
    desk: "city",
    tags: ["public-safety", "data", "sheriff"],
    sourceName: "Missoula County",
    sourceUrl: "https://www.missoulacounty.us/",
    sourceType: "Official",
    location: "Missoula County",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 192,
  }),
  S({
    headline: "City budget kickoff hearing scheduled for May 19",
    summary:
      "Council will hold its first FY2027 budget hearing May 19 at 6pm. Written comments accepted through the city clerk's office.",
    desk: "city",
    tags: ["budget", "city-council"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Missoula",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 240,
  }),
  S({
    headline: "Grant Creek trail extension receives $1.4M state award",
    summary:
      "Montana FWP awarded $1.4M toward the 1.8-mile Grant Creek Trail extension, closing a key gap in the North Hills network.",
    desk: "city",
    tags: ["trails", "grant", "parks"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Grant Creek",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 288,
  }),
  S({
    headline: "Missoula Redevelopment Agency approves Riverfront Triangle amendment",
    summary:
      "MRA board unanimously approved the revised urban renewal amendment for the Riverfront Triangle, clearing the next financing step.",
    desk: "city",
    tags: ["mra", "downtown", "redevelopment"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Downtown Missoula",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 336,
  }),
  S({
    headline: "Spring runoff forecast: Clark Fork near-normal, Bitterroot above",
    summary:
      "NRCS forecasts near-normal peak flows for the Clark Fork and 108% of median for the Bitterroot. Flood watch status: low.",
    desk: "city",
    tags: ["weather", "rivers", "nrcs"],
    sourceName: "KPAX",
    sourceUrl: "https://www.kpax.com/",
    sourceType: "Local News",
    location: "Western Montana",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 384,
  }),
  S({
    headline: "Missoula adopts revised short-term rental ordinance",
    summary:
      "Council passed updated STR rules requiring annual registration, primary-residence affidavit, and a 90-day non-owner cap.",
    whyItMatters:
      "Estimated 480 active STRs in the city limits — new rules expected to return a portion to long-term rental supply.",
    desk: "city",
    tags: ["housing", "str", "ordinance"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Missoula",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 480,
  }),
  S({
    headline: "Rattlesnake Wilderness trailhead parking expansion opens",
    summary:
      "The expanded Rattlesnake Main Trailhead lot adds 40 stalls, a bike corral, and a new vault toilet in time for the spring season.",
    desk: "city",
    tags: ["trails", "rattlesnake", "parks"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Rattlesnake",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 576,
  }),
  S({
    headline: "Missoula Police Department launches community dashboard",
    summary:
      "MPD's new public dashboard shows monthly use-of-force incidents, training hours, and response times by neighborhood.",
    desk: "city",
    tags: ["police", "transparency", "data"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Missoula",
    riskLevel: "high",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 624,
  }),

  // =========================
  // BUSINESS DESK
  // =========================
  S({
    headline: "Le Petit Outre announces second Missoula location",
    summary:
      "The beloved French bakery will open a second storefront on South Higgins this summer, adding morning counter service and a pastry program.",
    desk: "business",
    tags: ["bakery", "downtown", "opening"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "South Higgins",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 95,
  }),
  S({
    headline: "Downtown Missoula Partnership names 2026 retail grant winners",
    summary:
      "Seven small businesses received a combined $140,000 in facade and interior grants to refresh storefronts on Higgins and Main.",
    desk: "business",
    tags: ["downtown", "grants", "retail"],
    sourceName: "Downtown Missoula Partnership",
    sourceUrl: "https://www.missouladowntown.com/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 11,
  }),
  S({
    headline: "Onyx Hospitality opens new restaurant at Old Sawmill District",
    summary:
      "The Missoula-based restaurant group's newest concept — a wood-fired rotisserie — opened soft service Tuesday on Wyoming Street.",
    desk: "business",
    tags: ["restaurant", "old-sawmill", "opening"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Old Sawmill District",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 19,
  }),
  S({
    headline: "Missoula Chamber 2026 outlook: hiring slows, wages flat",
    summary:
      "Chamber's quarterly business pulse shows a 12-point drop in hiring intent and flat median wages — though retail confidence ticked up.",
    desk: "business",
    tags: ["chamber", "economy", "hiring"],
    sourceName: "Missoula Area Chamber of Commerce",
    sourceUrl: "https://www.missoulachamber.com/",
    sourceType: "Official",
    location: "Missoula",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 26,
  }),
  S({
    headline: "Draught Works to install solar array on Wyoming St. brewery",
    summary:
      "A 112 kW rooftop solar array will cover roughly 60% of the brewery's annual electric load, with installation wrapping in July.",
    desk: "business",
    tags: ["sustainability", "brewery", "solar"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Northside",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 33,
  }),
  S({
    headline: "Rockin Rudy's celebrates 44 years on Higgins",
    summary:
      "Missoula's independent record and gift store marked 44 years in business with a weekend sidewalk sale and live sets from local bands.",
    desk: "business",
    tags: ["retail", "downtown", "anniversary"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Downtown Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 44,
  }),
  S({
    headline: "Bitterroot Flyfishing Co. closes after 23 years",
    summary:
      "Owner Tom Kasun announced the shop will close May 31, citing retirement and rising downtown lease costs.",
    whyItMatters:
      "Third specialty outdoor retailer to close downtown in 12 months — part of a broader rent pressure trend on the 100-block of Higgins.",
    desk: "business",
    tags: ["retail", "downtown", "closing"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Downtown Missoula",
    status: "Developing",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 55,
  }),
  S({
    headline: "ClassPass Missoula expands partner roster to 38 studios",
    summary:
      "ClassPass added seven new Missoula studios this quarter, including two Pilates studios and a climbing gym in Midtown.",
    desk: "business",
    tags: ["fitness", "midtown", "expansion"],
    sourceName: "Missoula Area Chamber of Commerce",
    sourceUrl: "https://www.missoulachamber.com/",
    sourceType: "Official",
    location: "Midtown",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 68,
  }),
  S({
    headline: "AgriScience startup Pioneer Technical raises $6.2M Series A",
    summary:
      "The Missoula-based wildfire sensor startup closed a $6.2M Series A led by Seattle's Ascent Ventures with participation from Frontier Capital.",
    desk: "business",
    tags: ["startup", "funding", "climate"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Missoula",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 82,
  }),
  S({
    headline: "First Security Bank opens Reserve Street branch",
    summary:
      "The Missoula-headquartered bank opened its newest full-service branch on Reserve, adding 12 staff positions.",
    desk: "business",
    tags: ["banking", "reserve-street", "opening"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Reserve Street",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 108,
  }),
  S({
    headline: "BuyMissoula launches local-first gift card platform",
    summary:
      "Chamber's new universal gift card works at 74 Missoula-owned businesses and redirects a portion of every purchase into a small-business grant fund.",
    desk: "business",
    tags: ["local-first", "chamber", "gift-card"],
    sourceName: "Missoula Area Chamber of Commerce",
    sourceUrl: "https://www.missoulachamber.com/",
    sourceType: "Official",
    location: "Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 132,
  }),
  S({
    headline: "Big Dipper ice cream opens walk-up window for summer",
    summary:
      "The iconic Hip Strip shop's seasonal walk-up window reopened Friday with new flavors including Clark Fork Cold Brew and Huckleberry Hazelnut.",
    desk: "business",
    tags: ["hip-strip", "summer", "food"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Hip Strip",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 150,
  }),
  S({
    headline: "Southgate Mall unveils phase-two redevelopment designs",
    summary:
      "Owners Hendon Properties released renderings for phase two of the Southgate redevelopment, including 220 housing units and a central plaza.",
    desk: "business",
    tags: ["southgate", "redevelopment", "housing"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Southgate",
    status: "Developing",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 192,
  }),
  S({
    headline: "OrangeTheory Missoula relocating to larger Russell Street space",
    summary:
      "The Missoula studio will move from Brooks to Russell in late May, doubling its floor area and adding a recovery zone.",
    desk: "business",
    tags: ["fitness", "relocation"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Russell Street",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 240,
  }),
  S({
    headline: "Missoula unemployment holds steady at 2.9%",
    summary:
      "Montana DLI reported Missoula County unemployment unchanged at 2.9% in March; leisure and hospitality led job gains.",
    desk: "business",
    tags: ["economy", "labor", "data"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Missoula County",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 288,
  }),
  S({
    headline: "Noteworthy Paper & Press celebrates 10 years on Higgins",
    summary:
      "Missoula's letterpress stationery shop marks a decade downtown with a week of workshops and a collector's print release.",
    desk: "business",
    tags: ["downtown", "retail", "anniversary"],
    sourceName: "Downtown Missoula Partnership",
    sourceUrl: "https://www.missouladowntown.com/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 336,
  }),
  S({
    headline: "Bayern Brewing wins two medals at World Beer Cup",
    summary:
      "Missoula's Bayern Brewing took gold and silver at the 2026 World Beer Cup for its Doppelbock and Pilsener.",
    desk: "business",
    tags: ["brewery", "awards"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 408,
  }),
  S({
    headline: "Missoula coworking space Makerspace 406 expands to second floor",
    summary:
      "The Railway District coworking and maker space added 4,200 sq ft of private office suites, bringing total membership capacity to 180.",
    desk: "business",
    tags: ["coworking", "railway", "expansion"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Railway District",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 528,
  }),
  S({
    headline: "Montana Farmers Union opens Missoula regional office",
    summary:
      "MFU's new Missoula office will serve western Montana producers with policy advocacy and cooperative support services.",
    desk: "business",
    tags: ["agriculture", "opening"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/",
    sourceType: "Local News",
    location: "Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 612,
  }),

  // =========================
  // CULTURE DESK
  // =========================
  S({
    headline: "Top Hat Lounge announces summer outdoor concert series",
    summary:
      "The Top Hat will host 14 free outdoor concerts in Caras Park this summer, opening June 6 with The California Honeydrops.",
    desk: "culture",
    tags: ["music", "caras-park", "summer"],
    sourceName: "Destination Missoula",
    sourceUrl: "https://www.destinationmissoula.org/",
    sourceType: "Community Calendar",
    location: "Caras Park",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 28,
  }),
  S({
    headline: "Missoula Art Museum opens 'Rivers & Light' exhibit",
    summary:
      "MAM's new survey of contemporary Montana landscape artists opened Saturday with works by 12 regional painters and photographers.",
    desk: "culture",
    tags: ["art", "museum", "exhibit"],
    sourceName: "Missoula Art Museum",
    sourceUrl: "https://www.missoulaartmuseum.org/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 4,
  }),
  S({
    headline: "International Wildlife Film Festival returns May 3–10",
    summary:
      "The 49th annual IWFF kicks off May 3 with 82 films, filmmaker Q&As, and an outdoor screening on the Wilma lawn.",
    desk: "culture",
    tags: ["film", "festival", "wildlife"],
    sourceName: "Destination Missoula",
    sourceUrl: "https://www.destinationmissoula.org/",
    sourceType: "Community Calendar",
    location: "Downtown Missoula",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 13,
  }),
  S({
    headline: "Missoula Symphony announces 2026–27 season",
    summary:
      "The symphony's 72nd season includes collaborations with the Montana Repertory Theatre and a commissioned work from composer Gabriella Smith.",
    desk: "culture",
    tags: ["symphony", "classical", "season"],
    sourceName: "Missoula Symphony",
    sourceUrl: "https://missoulasymphony.org/",
    sourceType: "Official",
    location: "Dennison Theatre",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 22,
  }),
  S({
    headline: "Out to Lunch series returns to Caras Park May 7",
    summary:
      "Missoula's beloved Wednesday lunchtime music-and-food series returns May 7 with 30+ food vendors scheduled across the season.",
    desk: "culture",
    tags: ["out-to-lunch", "caras-park", "summer"],
    sourceName: "Missoula Downtown Partnership",
    sourceUrl: "https://www.missouladowntown.com/",
    sourceType: "Community Calendar",
    location: "Caras Park",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 30,
  }),
  S({
    headline: "Missoula Children's Theatre casts community production of 'The Secret Garden'",
    summary:
      "MCT open casting drew 180 local kids; performances run June 14–22 at the MCT Center for Performing Arts.",
    desk: "culture",
    tags: ["theatre", "family", "community"],
    sourceName: "Missoula Children's Theatre",
    sourceUrl: "https://mctinc.org/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 40,
  }),
  S({
    headline: "River City Roots Festival lineup announced",
    summary:
      "The August 22–24 festival will headline with Mavis Staples and Charley Crockett; full lineup and free stages posted online.",
    desk: "culture",
    tags: ["festival", "music", "downtown"],
    sourceName: "Missoula Downtown Partnership",
    sourceUrl: "https://www.missouladowntown.com/",
    sourceType: "Community Calendar",
    location: "Downtown Missoula",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 56,
  }),
  S({
    headline: "Farmers Market opens downtown Saturday",
    summary:
      "Missoula Farmers Market's 55th season opens Saturday at 8am. 78 vendors confirmed including four new flower growers.",
    desk: "culture",
    tags: ["farmers-market", "downtown", "food"],
    sourceName: "Missoula Farmers Market",
    sourceUrl: "https://missoulafarmersmarket.com/",
    sourceType: "Community Calendar",
    location: "Circle Square",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 72,
  }),
  S({
    headline: "Missoula Public Library unveils 'Books Across Montana' program",
    summary:
      "A new mail-based lending program extends MPL's collection to rural Montana residents without local library access.",
    desk: "culture",
    tags: ["library", "rural", "literacy"],
    sourceName: "Missoula Public Library",
    sourceUrl: "https://www.missoulapubliclibrary.org/",
    sourceType: "Official",
    location: "Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 96,
  }),
  S({
    headline: "Wilma lineup: Khruangbin, Kurt Vile, Brittany Howard this summer",
    summary:
      "The Wilma announced 18 new summer shows, with headliners Khruangbin (June 12), Kurt Vile (July 9), and Brittany Howard (August 3).",
    desk: "culture",
    tags: ["music", "wilma", "concerts"],
    sourceName: "The Wilma",
    sourceUrl: "https://www.logjampresents.com/",
    sourceType: "Community Calendar",
    location: "Downtown Missoula",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 110,
  }),
  S({
    headline: "Zootown Arts Community Center expands youth program",
    summary:
      "ZACC will open six new summer camps covering animation, letterpress, and textile arts, with scholarships for 40% of seats.",
    desk: "culture",
    tags: ["zacc", "youth", "arts"],
    sourceName: "Zootown Arts Community Center",
    sourceUrl: "https://zootownarts.org/",
    sourceType: "Official",
    location: "Westside",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 140,
  }),
  S({
    headline: "Missoula Insectarium hatches rare blue morpho butterflies",
    summary:
      "Two blue morpho butterflies emerged this week at Missoula's Insectarium, marking the first successful in-house hatch of the species.",
    desk: "culture",
    tags: ["insectarium", "family", "science"],
    sourceName: "KPAX",
    sourceUrl: "https://www.kpax.com/",
    sourceType: "Local News",
    location: "Downtown Missoula",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 168,
  }),
  S({
    headline: "Garden City Brewfest returns to Caras Park May 10",
    summary:
      "The 30th annual Brewfest features 75 Montana breweries and cideries, live music, and food trucks on the riverfront.",
    desk: "culture",
    tags: ["brewfest", "caras-park", "festival"],
    sourceName: "Destination Missoula",
    sourceUrl: "https://www.destinationmissoula.org/",
    sourceType: "Community Calendar",
    location: "Caras Park",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 200,
  }),
  S({
    headline: "Missoula Writes: spring lit festival wraps with record attendance",
    summary:
      "The three-day literary festival drew 3,400 attendees and featured Pulitzer winner Jennifer Egan in conversation with local poet Melissa Kwasny.",
    desk: "culture",
    tags: ["books", "festival", "literature"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Downtown Missoula",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 240,
  }),
  S({
    headline: "Missoula Fairgrounds spring home & garden show this weekend",
    summary:
      "125 vendors will fill the First Interstate Center Saturday and Sunday, 10am–5pm. Parking free; admission $5.",
    desk: "culture",
    tags: ["fairgrounds", "home-garden", "event"],
    sourceName: "Missoula County Fairgrounds",
    sourceUrl: "https://missoulafairgrounds.com/",
    sourceType: "Community Calendar",
    location: "Missoula Fairgrounds",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 264,
  }),
  S({
    headline: "Butte to Missoula craft beer train announces 2026 dates",
    summary:
      "The annual 90-minute craft beer train between Missoula and Butte returns June 21 with four Montana breweries onboard.",
    desk: "culture",
    tags: ["craft-beer", "train", "event"],
    sourceName: "Destination Missoula",
    sourceUrl: "https://www.destinationmissoula.org/",
    sourceType: "Community Calendar",
    location: "Missoula",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 312,
  }),
  S({
    headline: "University of Montana spring commencement set for May 9",
    summary:
      "More than 1,900 graduates will walk Adams Center stage May 9; keynote by astronaut and UM alum Mike Fincke.",
    desk: "culture",
    tags: ["um", "commencement", "education"],
    sourceName: "University of Montana",
    sourceUrl: "https://www.umt.edu/",
    sourceType: "Official",
    location: "Adams Center",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 360,
  }),
  S({
    headline: "Missoula Mercantile history walk returns weekly",
    summary:
      "Historical Museum at Fort Missoula's guided Mercantile block history walk resumes every Saturday through September.",
    desk: "culture",
    tags: ["history", "walking-tour", "downtown"],
    sourceName: "Historical Museum at Fort Missoula",
    sourceUrl: "https://fortmissoulamuseum.org/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 432,
  }),
  S({
    headline: "Saturday Market announces 2026 vendor roster",
    summary:
      "Missoula Saturday Market returns May 3 with 160 vendors, including 24 first-timers specializing in ceramics and small-batch food.",
    desk: "culture",
    tags: ["market", "downtown", "craft"],
    sourceName: "Missoula Downtown Partnership",
    sourceUrl: "https://www.missouladowntown.com/",
    sourceType: "Community Calendar",
    location: "Downtown Missoula",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 504,
  }),
  S({
    headline: "Missoula PrideFest 2026 announces June 20 kickoff",
    summary:
      "Western Montana LGBTQ+ Community Center released the June 20–22 PrideFest schedule, headlined by a Caras Park block party and pride march.",
    desk: "culture",
    tags: ["pride", "festival", "community"],
    sourceName: "Destination Missoula",
    sourceUrl: "https://www.destinationmissoula.org/",
    sourceType: "Community Calendar",
    location: "Downtown Missoula",
    status: "Event",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 576,
  }),
  S({
    headline: "Montana Natural History Center's 'Frogs!' exhibit opens",
    summary:
      "The new seasonal exhibit features nine native frog species and interactive stations on Montana's wetland ecosystems.",
    desk: "culture",
    tags: ["museum", "science", "family"],
    sourceName: "Montana Natural History Center",
    sourceUrl: "https://www.montananaturalist.org/",
    sourceType: "Official",
    location: "Downtown Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 648,
  }),

  // A few cross-desk adjacent items
  S({
    headline: "Bonner Park pickleball courts reopen after resurfacing",
    summary:
      "Parks & Rec finished resurfacing Bonner Park's four pickleball courts; open play returns Wednesday with new LED court lighting.",
    desk: "city",
    tags: ["parks", "pickleball", "rattlesnake"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/",
    sourceType: "Official",
    location: "Bonner Park",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 720,
  }),

  // =========================
  // SPORTS DESK (Griz, recreation, high school, marathons)
  // =========================
  S({
    headline: "Griz football opens fall camp with new offensive coordinator",
    summary:
      "University of Montana football opened fall camp at Washington-Grizzly Stadium with new OC Brian Armstrong installing a faster-tempo offense ahead of the FCS season opener.",
    whyItMatters:
      "Griz home games drive an estimated $20M into the Missoula economy each season. A faster offense could change ticket demand and travel patterns.",
    desk: "sports",
    tags: ["griz", "football", "university-of-montana"],
    sourceName: "Montana Grizzlies Athletics",
    sourceUrl: "https://gogriz.com/",
    sourceType: "Official",
    location: "Washington-Grizzly Stadium",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 35,
  }),
  S({
    headline: "Lady Griz basketball signs three-star transfer guard",
    summary:
      "Lady Griz announced the addition of a three-star transfer guard from Boise State, addressing perimeter shooting needs heading into Big Sky play.",
    desk: "sports",
    tags: ["lady-griz", "basketball", "recruiting"],
    sourceName: "Montana Grizzlies Athletics",
    sourceUrl: "https://gogriz.com/",
    sourceType: "Official",
    location: "Adams Center",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 95,
  }),
  S({
    headline: "Missoula Marathon registration tops 4,500 runners",
    summary:
      "Race organizers say registration for the 2026 Missoula Marathon has surpassed 4,500 runners, with the half-marathon already at capacity. Volunteer signup opens next week.",
    whyItMatters:
      "The marathon weekend fills hotels and downtown restaurants, traditionally the city's biggest summer tourism revenue weekend.",
    desk: "sports",
    tags: ["marathon", "running", "tourism"],
    sourceName: "Destination Missoula",
    sourceUrl: "https://www.destinationmissoula.org/",
    sourceType: "Community Calendar",
    location: "Downtown Missoula",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 180,
  }),
  S({
    headline: "Hellgate boys soccer wins state Class AA championship",
    summary:
      "Hellgate High School defeated Bozeman 2-1 in overtime to claim the Class AA state soccer title — their first since 2019.",
    desk: "sports",
    tags: ["high-school", "soccer", "hellgate"],
    sourceName: "Missoulian",
    sourceUrl: "https://missoulian.com/sports/",
    sourceType: "Local News",
    location: "Bozeman",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 240,
  }),
  S({
    headline: "Parks & Rec adult kickball league sells out in 48 hours",
    summary:
      "Missoula Parks & Recreation says all 24 spots in the summer adult co-ed kickball league filled in under two days. A waitlist is open for late drops.",
    desk: "sports",
    tags: ["parks-rec", "recreation", "kickball"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/229/Parks-Recreation",
    sourceType: "Official",
    location: "Playfair Park",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 320,
  }),
  S({
    headline: "Big Sky Conference adds women's wrestling for 2027 season",
    summary:
      "The Big Sky Conference voted to sanction women's wrestling beginning in 2027, with Montana already committing to a varsity program.",
    desk: "sports",
    tags: ["big-sky", "wrestling", "griz"],
    sourceName: "Montana Grizzlies Athletics",
    sourceUrl: "https://gogriz.com/",
    sourceType: "Official",
    location: "Adams Center",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 480,
  }),
  S({
    headline: "River Bowl cyclocross race draws record crowd to Kim Williams Trail",
    summary:
      "Sunday's River Bowl cyclocross event drew a record 320 racers and an estimated 1,200 spectators to the Kim Williams Trail along the Clark Fork.",
    desk: "sports",
    tags: ["cycling", "cyclocross", "clark-fork"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Kim Williams Trail",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 600,
  }),
  S({
    headline: "Sentinel Spartans baseball clinches Western AA division",
    summary:
      "Sentinel High clinched the Western AA division title with a 7-3 win over Big Sky, securing the #1 playoff seed for the second straight year.",
    desk: "sports",
    tags: ["high-school", "baseball", "sentinel"],
    sourceName: "KPAX",
    sourceUrl: "https://www.kpax.com/sports",
    sourceType: "Local News",
    location: "Sentinel High",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 18,
  }),
  S({
    headline: "Griz softball announces 2026 home schedule",
    summary:
      "Montana softball released its 2026 home schedule featuring 24 home dates at Grant Field, including a Senior Day doubleheader against rival Montana State.",
    desk: "sports",
    tags: ["griz", "softball", "schedule"],
    sourceName: "Montana Grizzlies Athletics",
    sourceUrl: "https://gogriz.com/",
    sourceType: "Official",
    location: "Grant Field",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 24,
  }),
  S({
    headline: "Missoula youth hockey program expands with new ice slot at Glacier",
    summary:
      "Missoula Junior Bruins added a fourth weekly ice slot at Glacier Ice Rink to accommodate growing enrollment in the U10 and U12 divisions.",
    desk: "sports",
    tags: ["youth", "hockey", "recreation"],
    sourceName: "City of Missoula",
    sourceUrl: "https://www.ci.missoula.mt.us/229/Parks-Recreation",
    sourceType: "Official",
    location: "Glacier Ice Rink",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 36,
  }),
  S({
    headline: "Big Sky Trail Run Series opens 2026 calendar with Blue Mountain race",
    summary:
      "The Big Sky Trail Run Series kicks off May 2 with the Blue Mountain Half on Pattee Canyon trails, the first of seven local races through October.",
    desk: "sports",
    tags: ["trail-running", "events", "pattee-canyon"],
    sourceName: "Destination Missoula",
    sourceUrl: "https://www.destinationmissoula.org/",
    sourceType: "Community Calendar",
    location: "Pattee Canyon",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 48,
  }),

  // =========================
  // HEALTH DESK
  // Public health + wellness + breakthrough medicine + health-tech announcements
  // =========================
  S({
    headline: "FDA approves new Alzheimer's drug shown to slow decline by 35%",
    summary:
      "The FDA approved donanemab follow-on therapy after Phase III data showed a 35% slowing of cognitive decline in early-stage Alzheimer's patients. Providence St. Patrick is among the first regional hospitals enrolling.",
    whyItMatters:
      "Roughly 22,000 Montanans live with Alzheimer's. Local enrollment means Missoula patients can access the therapy without traveling out of state.",
    desk: "health",
    tags: ["breakthrough-medicine", "fda", "alzheimers", "providence"],
    sourceName: "Providence St. Patrick Hospital",
    sourceUrl: "https://www.providence.org/locations/mt/st-patrick-hospital",
    sourceType: "Official",
    location: "Providence St. Patrick",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 25,
  }),
  S({
    headline: "Community Medical Center launches AI-assisted radiology pilot",
    summary:
      "Community Medical Center is piloting an FDA-cleared AI system that flags suspicious lung nodules on CT scans within seconds, with all results reviewed by a board-certified radiologist.",
    whyItMatters:
      "Earlier flagging shaves hours-to-days off the diagnostic timeline for at-risk patients — critical in a region with limited specialist density.",
    desk: "health",
    tags: ["breakthrough-medicine", "ai", "radiology", "health-tech"],
    sourceName: "Community Medical Center",
    sourceUrl: "https://www.communitymed.org/",
    sourceType: "Official",
    location: "Community Medical Center",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 75,
  }),
  S({
    headline: "Sickle cell gene therapy now available regionally after Casgevy approval",
    summary:
      "Following FDA approval of CRISPR-based Casgevy, the regional bone-marrow program announced it will offer the one-time gene therapy to eligible Montana patients via a Seattle partner site.",
    whyItMatters:
      "Sickle cell affects ~80 known patients in western Montana. Casgevy is the first FDA-approved CRISPR therapy and can functionally cure the disease.",
    desk: "health",
    tags: ["breakthrough-medicine", "crispr", "gene-therapy", "sickle-cell"],
    sourceName: "Providence St. Patrick Hospital",
    sourceUrl: "https://www.providence.org/locations/mt/st-patrick-hospital",
    sourceType: "Official",
    location: "Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 140,
  }),
  S({
    headline: "GLP-1 trial at UM enrolls 200 Montanans for cardiovascular study",
    summary:
      "University of Montana's School of Pharmacy is enrolling 200 patients with cardiovascular risk into a multi-site Phase IV trial testing GLP-1 medications for non-diabetic outcomes.",
    whyItMatters:
      "GLP-1 drugs are reshaping obesity and cardiovascular care nationally. Local enrollment gives Montanans access to the next wave of evidence and care.",
    desk: "health",
    tags: ["breakthrough-medicine", "glp-1", "clinical-trial", "university-of-montana"],
    sourceName: "University of Montana",
    sourceUrl: "https://www.umt.edu/news/",
    sourceType: "Official",
    location: "UM Skaggs School of Pharmacy",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 220,
  }),
  S({
    headline: "Continuous glucose monitors expanding to non-diabetic primary care here",
    summary:
      "Two Missoula primary-care groups began offering wearable continuous glucose monitors to non-diabetic patients for short-term metabolic-health screening, following the FDA's 2024 OTC clearance of Stelo and Lingo.",
    desk: "health",
    tags: ["breakthrough-medicine", "wearables", "cgm", "primary-care"],
    sourceName: "Missoula City-County Health Department",
    sourceUrl: "https://www.missoulainfo.com/",
    sourceType: "Official",
    location: "Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 360,
  }),
  S({
    headline: "City-County Health Dept warns of measles uptick in western Montana",
    summary:
      "Missoula City-County Health Department confirmed three new measles cases in unvaccinated travelers and urged residents to verify MMR status, especially for children ages 1-6.",
    whyItMatters:
      "Measles spreads aggressively in undervaccinated communities. Public-health officials say the next two weeks are critical for containment.",
    desk: "health",
    tags: ["public-health", "measles", "vaccination"],
    sourceName: "Missoula City-County Health Department",
    sourceUrl: "https://www.missoulainfo.com/",
    sourceType: "Official",
    location: "Missoula County",
    status: "Developing",
    riskLevel: "high",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 50,
  }),
  S({
    headline: "Free mental-health walk-in clinic opens at the YWCA",
    summary:
      "YWCA Missoula partnered with Western Montana Mental Health to open a no-appointment, no-cost walk-in mental-health clinic Wednesdays from 1-5 p.m.",
    desk: "health",
    tags: ["mental-health", "public-health", "ywca"],
    sourceName: "YWCA Missoula",
    sourceUrl: "https://www.ywcaofmissoula.org/",
    sourceType: "Official",
    location: "YWCA Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 420,
  }),
  S({
    headline: "Air-quality smoke advisory lifted after weekend rain",
    summary:
      "Missoula City-County Health Department lifted its air-quality smoke advisory after weekend rain dropped fine-particulate readings to Good across all monitoring sites.",
    desk: "health",
    tags: ["public-health", "air-quality", "wildfire-smoke"],
    sourceName: "Missoula City-County Health Department",
    sourceUrl: "https://www.missoulainfo.com/",
    sourceType: "Official",
    location: "Missoula Valley",
    status: "Updated",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 540,
  }),
  S({
    headline: "Providence opens new outpatient cancer center in Missoula",
    summary:
      "Providence St. Patrick opened a new 28,000-sq-ft outpatient cancer center on Broadway, consolidating infusion, imaging, and radiation oncology under one roof.",
    whyItMatters:
      "Reduces multi-site travel for cancer patients across western Montana — a known barrier to treatment completion in the region.",
    desk: "health",
    tags: ["healthcare", "providence", "cancer-care"],
    sourceName: "Providence St. Patrick Hospital",
    sourceUrl: "https://www.providence.org/locations/mt/st-patrick-hospital",
    sourceType: "Official",
    location: "Broadway",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 14,
  }),
  S({
    headline: "UM researchers publish wildfire-smoke + lung-function study",
    summary:
      "University of Montana researchers published a peer-reviewed study linking repeated wildfire-smoke exposure to measurable long-term lung-function decline in western Montana children.",
    desk: "health",
    tags: ["public-health", "research", "wildfire-smoke", "university-of-montana"],
    sourceName: "University of Montana",
    sourceUrl: "https://www.umt.edu/news/",
    sourceType: "Official",
    location: "UM Campus",
    status: "New",
    riskLevel: "medium",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 30,
  }),
  S({
    headline: "Free CPR/AED training Saturday at the Missoula Public Library",
    summary:
      "American Red Cross Montana is offering a free hands-only CPR and AED training session Saturday from 10 a.m. to noon at the Missoula Public Library. No registration required.",
    desk: "health",
    tags: ["public-health", "cpr", "community"],
    sourceName: "Missoula Public Library",
    sourceUrl: "https://missoulapubliclibrary.org/",
    sourceType: "Official",
    location: "Missoula Public Library",
    status: "Event",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 4,
  }),
  S({
    headline: "Wearable-data startup spins out of UM with Series A round",
    summary:
      "Missoula-based health-tech startup PeakVitals closed a $12M Series A to expand its wearable-data platform that predicts overtraining injuries in college athletes; UM will be the launch partner.",
    desk: "health",
    tags: ["breakthrough-medicine", "health-tech", "wearables", "startups"],
    sourceName: "Missoula Current",
    sourceUrl: "https://missoulacurrent.com/",
    sourceType: "Local News",
    location: "Missoula",
    status: "New",
    riskLevel: "low",
    isSeeded: true,
    modState: "approved",
    minutesAgo: 60 * 50,
  }),
];

export const SEED_EVENTS: Array<Omit<InsertEvent, "startsAt"> & { hoursFromNow: number; desk?: string; description?: string }> = [
  // Culture / arts
  { title: "Out to Lunch — Opening Week", venue: "Caras Park", sourceName: "Missoula Downtown Partnership", sourceUrl: "https://www.missouladowntown.com/", tag: "music", desk: "culture", description: "The Wednesday lunchtime series returns with 14 food vendors and live music.", hoursFromNow: 48 },
  { title: "Garden City Brewfest", venue: "Missoula County Fairgrounds", sourceName: "Destination Missoula", sourceUrl: "https://www.destinationmissoula.org/", tag: "festival", desk: "culture", description: "60+ Montana breweries, cideries, and distilleries pour at the 16th annual festival.", hoursFromNow: 96 },
  { title: "Missoula Art Museum — First Friday", venue: "Missoula Art Museum", sourceName: "Missoula Art Museum", sourceUrl: "https://www.missoulaartmuseum.org/", tag: "art", desk: "culture", description: "Free monthly open house featuring rotating exhibitions and artist talks.", hoursFromNow: 168 },
  { title: "International Wildlife Film Festival", venue: "The Wilma", sourceName: "Destination Missoula", sourceUrl: "https://www.destinationmissoula.org/", tag: "film", desk: "culture", description: "Week-long screenings of the best in wildlife cinema.", hoursFromNow: 288 },
  { title: "ZACC Summer Residency Opening Reception", venue: "ZACC", sourceName: "Zootown Arts Community Center", sourceUrl: "https://zootownarts.org/", tag: "art", desk: "culture", description: "Meet the eight artists joining the ZACC's summer residency cohort.", hoursFromNow: 360 },
  { title: "River City Roots Festival", venue: "Downtown Missoula", sourceName: "Destination Missoula", sourceUrl: "https://www.destinationmissoula.org/", tag: "festival", desk: "culture", description: "Free two-day downtown festival with music, art, and food.", hoursFromNow: 24 * 90 },

  // City / civic
  { title: "City Council Budget Hearing", venue: "Council Chambers", sourceName: "City of Missoula", sourceUrl: "https://www.ci.missoula.mt.us/", tag: "civic", desk: "city", description: "Public hearing on the FY27 preliminary budget.", hoursFromNow: 192 },
  { title: "County Commissioner Public Hearing — Subdivision Rules", venue: "County Courthouse", sourceName: "Missoula County", sourceUrl: "https://www.missoulacounty.us/", tag: "civic", desk: "city", description: "Public comment on proposed amendments to the county's subdivision regulations.", hoursFromNow: 144 },
  { title: "MCPS School Board Meeting", venue: "MCPS Admin Building", sourceName: "City of Missoula", sourceUrl: "https://www.ci.missoula.mt.us/", tag: "civic", desk: "city", description: "Regular monthly meeting. Agenda includes cellphone policy review.", hoursFromNow: 216 },
  { title: "Planning Board Work Session", venue: "Council Chambers", sourceName: "City of Missoula", sourceUrl: "https://www.ci.missoula.mt.us/", tag: "civic", desk: "city", description: "Work session on growth-policy update, open to the public.", hoursFromNow: 456 },

  // Business
  { title: "Saturday Market Opening Day", venue: "Circle Square", sourceName: "Missoula Downtown Partnership", sourceUrl: "https://www.missouladowntown.com/", tag: "market", desk: "business", description: "80+ local vendors kick off the 2026 season.", hoursFromNow: 240 },
  { title: "Chamber Small Business Awards Luncheon", venue: "DoubleTree Hotel", sourceName: "Missoula Area Chamber of Commerce", sourceUrl: "https://www.missoulachamber.com/", tag: "business", desk: "business", description: "Annual luncheon recognizing Missoula's outstanding small businesses.", hoursFromNow: 312 },
  { title: "Coworking Community Open House", venue: "North Higgins", sourceName: "Missoula Downtown Partnership", sourceUrl: "https://www.missouladowntown.com/", tag: "business", desk: "business", description: "Tour the new Backwater Works coworking space.", hoursFromNow: 408 },

  // Crime / public safety
  { title: "Community Safety Town Hall — MPD", venue: "Missoula Public Library", sourceName: "Missoula Police Department", sourceUrl: "https://www.ci.missoula.mt.us/228/Police", tag: "public safety", desk: "crime", description: "Hosted by Missoula Police. Open Q&A with Chief of Police and neighborhood officers.", hoursFromNow: 120 },
  { title: "Sheriff's Office Citizen Academy — Info Night", venue: "Missoula County Sheriff's Office", sourceName: "Missoula County Sheriff", sourceUrl: "https://www.missoulacounty.us/", tag: "public safety", desk: "crime", description: "Overview of the fall Citizen Academy program. Applications open.", hoursFromNow: 264 },
  { title: "Missoula Neighborhood Watch Quarterly", venue: "City-County Health Building", sourceName: "Missoula Police Department", sourceUrl: "https://www.ci.missoula.mt.us/228/Police", tag: "public safety", desk: "crime", description: "Quarterly meeting of Missoula neighborhood watch captains.", hoursFromNow: 480 },

  // Community / feel-good
  { title: "United Way Day of Action", venue: "Citywide", sourceName: "United Way of Missoula County", sourceUrl: "https://www.missoulaunitedway.org/", tag: "community", desk: "community", description: "Volunteer service across 14 project sites. All ages welcome.", hoursFromNow: 72 },
  { title: "Missoula Food Bank Volunteer Orientation", venue: "Missoula Food Bank — Mullan Trail", sourceName: "Missoula Food Bank", sourceUrl: "https://missoulafoodbank.org/", tag: "community", desk: "community", description: "New-volunteer orientation for weekend distribution shifts.", hoursFromNow: 96 },
  { title: "YMCA Family Fun Run", venue: "Caras Park", sourceName: "YMCA Missoula", sourceUrl: "https://www.ymcamissoula.org/", tag: "community", desk: "community", description: "Free 5K supporting YMCA camp scholarships.", hoursFromNow: 336 },
  { title: "Community Supper for Veterans & Families", venue: "Rocky Mountain Elks Lodge", sourceName: "United Way of Missoula County", sourceUrl: "https://www.missoulaunitedway.org/", tag: "community", desk: "community", description: "Free meal with live music, hosted by local VFW posts.", hoursFromNow: 504 },

  // Politics / elections
  { title: "Ward 4 City Council Candidate Forum", venue: "Missoula Public Library", sourceName: "Missoula County Elections", sourceUrl: "https://www.missoulacounty.us/", tag: "politics", desk: "politics", description: "Candidate forum for the open Ward 4 city council seat. Each candidate will answer resident questions.", hoursFromNow: 168 },
  { title: "Voter Registration Deadline — May Election", venue: "Missoula County Elections Office", sourceName: "Missoula County Elections", sourceUrl: "https://www.missoulacounty.us/", tag: "politics", desk: "politics", description: "Last day to register, update name/address, or change party affiliation ahead of the May primary.", hoursFromNow: 160 },
  { title: "Mayoral Debate — Hosted by MCAT", venue: "MCAT Studio", sourceName: "Missoula County Elections", sourceUrl: "https://www.missoulacounty.us/", tag: "politics", desk: "politics", description: "Televised debate with all qualified mayoral candidates. Submit questions in advance.", hoursFromNow: 384 },
  { title: "May Municipal Election — Election Day", venue: "Missoula County", sourceName: "Missoula County Elections", sourceUrl: "https://www.missoulacounty.us/", tag: "politics", desk: "politics", description: "Ballots must be returned to a drop box or polling place by 8 p.m.", hoursFromNow: 24 * 21 },
  { title: "School Board Candidate Meet & Greet", venue: "Hellgate High School", sourceName: "Missoula County Elections", sourceUrl: "https://www.missoulacounty.us/", tag: "politics", desk: "politics", description: "Informal meet-and-greet with all candidates for MCPS school board trustee seats.", hoursFromNow: 24 * 14 },

  // Sports
  { title: "Griz Spring Football Showcase", venue: "Washington-Grizzly Stadium", sourceName: "Montana Grizzlies Athletics", sourceUrl: "https://gogriz.com/", tag: "griz", desk: "sports", description: "Free open practice and skills competition with the 2026 Griz football roster.", hoursFromNow: 96 },
  { title: "Missoula Marathon — Race Weekend", venue: "Downtown Missoula", sourceName: "Destination Missoula", sourceUrl: "https://www.destinationmissoula.org/", tag: "running", desk: "sports", description: "Full marathon, half, 5K, and kids race across the weekend.", hoursFromNow: 24 * 75 },
  { title: "Big Sky Trail Run — Blue Mountain Half", venue: "Pattee Canyon", sourceName: "Destination Missoula", sourceUrl: "https://www.destinationmissoula.org/", tag: "trail-running", desk: "sports", description: "Series opener: 13.1-mile trail half on Blue Mountain.", hoursFromNow: 24 * 9 },
  { title: "Lady Griz vs. Idaho State", venue: "Adams Center", sourceName: "Montana Grizzlies Athletics", sourceUrl: "https://gogriz.com/", tag: "basketball", desk: "sports", description: "Big Sky home opener.", hoursFromNow: 24 * 32 },
  { title: "Hellgate vs. Big Sky High — Crosstown Soccer", venue: "MCPS Sports Complex", sourceName: "Missoulian", sourceUrl: "https://missoulian.com/sports/", tag: "high-school", desk: "sports", description: "Crosstown rivalry match. Free admission for students.", hoursFromNow: 60 },

  // Health
  { title: "Free Community CPR + AED Training", venue: "Missoula Public Library", sourceName: "Missoula Public Library", sourceUrl: "https://missoulapubliclibrary.org/", tag: "public-health", desk: "health", description: "Hands-only CPR and AED training. No registration required.", hoursFromNow: 80 },
  { title: "Walk-In Mental Health Clinic", venue: "YWCA Missoula", sourceName: "YWCA Missoula", sourceUrl: "https://www.ywcaofmissoula.org/", tag: "mental-health", desk: "health", description: "No-cost walk-in mental-health support every Wednesday.", hoursFromNow: 168 },
  { title: "Providence Health & Wellness Fair", venue: "Providence St. Patrick Hospital", sourceName: "Providence St. Patrick Hospital", sourceUrl: "https://www.providence.org/locations/mt/st-patrick-hospital", tag: "public-health", desk: "health", description: "Free blood-pressure screening, BMI checks, nutrition counseling.", hoursFromNow: 24 * 12 },
  { title: "GLP-1 Cardiovascular Trial Info Session", venue: "UM Skaggs School of Pharmacy", sourceName: "University of Montana", sourceUrl: "https://www.umt.edu/news/", tag: "breakthrough-medicine", desk: "health", description: "Open info session for prospective trial participants.", hoursFromNow: 24 * 18 },
];

// Real Missoula sources. Where an RSS/Atom feed exists, `feedUrl` + `feedType: "rss"`
// is used; for sources without feeds, `feedType: "html"` with a `parserKey` identifies
// the scraper module. If the live fetch fails, the ingester falls back to a fixtures file.
// Helper for compact source rows.
function src(
  name: string,
  url: string,
  opts: {
    feedUrl?: string | null;
    feedType?: "rss" | "atom" | "html" | "none";
    parserKey?: string | null;
    sourceType: "Official" | "Local News" | "Community Calendar" | "Social Media";
    desks: string[];
    cadence: number;
    category: "official" | "news" | "calendars" | "social";
    handle?: string | null;
    platform?: "x" | "facebook" | "instagram" | "youtube" | null;
  },
): InsertSource {
  return {
    name,
    url,
    feedUrl: opts.feedUrl ?? null,
    feedType: (opts.feedType ?? "none") as any,
    parserKey: opts.parserKey ?? null,
    sourceType: opts.sourceType,
    desks: JSON.stringify(opts.desks),
    cadenceMinutes: opts.cadence,
    lastCheckedAt: null,
    lastStatus: "idle",
    lastMode: null,
    lastError: null,
    lastItems: 0,
    active: true,
    category: opts.category,
    handle: opts.handle ?? null,
    platform: opts.platform ?? null,
  };
}

export const SEED_SOURCES: InsertSource[] = [
  // ============ NEWS ============
  src("Missoulian", "https://missoulian.com/", { feedUrl: "https://missoulian.com/search/?f=rss&t=article&l=25&s=start_time&sd=desc", feedType: "rss", sourceType: "Local News", desks: ["city", "business", "culture", "crime", "community", "politics", "sports", "health"], cadence: 5, category: "news" }),
  src("Missoula Current", "https://missoulacurrent.com/", { feedUrl: "https://missoulacurrent.com/feed/", feedType: "rss", sourceType: "Local News", desks: ["city", "business", "culture", "crime", "community", "politics", "sports", "health"], cadence: 5, category: "news" }),
  src("KPAX", "https://www.kpax.com/", { feedUrl: "https://www.kpax.com/news.rss", feedType: "rss", sourceType: "Local News", desks: ["city", "culture", "crime", "community", "politics", "sports", "health"], cadence: 5, category: "news" }),
  src("Montana Free Press", "https://montanafreepress.org/", { feedUrl: "https://montanafreepress.org/feed/", feedType: "rss", sourceType: "Local News", desks: ["politics", "city", "business", "health"], cadence: 30, category: "news" }),

  // ============ OFFICIAL ============
  src("City of Missoula", "https://www.ci.missoula.mt.us/", { feedUrl: "https://www.ci.missoula.mt.us/RSSFeed.aspx?ModID=1&CID=All-0", feedType: "rss", sourceType: "Official", desks: ["city"], cadence: 10, category: "official" }),
  src("Missoula County", "https://www.missoulacounty.us/", { feedUrl: "https://www.missoulacounty.us/RSSFeed.aspx?ModID=1&CID=All-0", feedType: "rss", sourceType: "Official", desks: ["city"], cadence: 10, category: "official" }),
  src("Missoula Police Department", "https://www.ci.missoula.mt.us/228/Police", { feedUrl: "https://www.ci.missoula.mt.us/RSSFeed.aspx?ModID=1&CID=Police-Department-16", feedType: "rss", sourceType: "Official", desks: ["crime", "city"], cadence: 10, category: "official" }),
  src("Missoula County Sheriff", "https://www.missoulacounty.us/government/law-justice-public-safety/sheriff", { feedUrl: "https://www.missoulacounty.us/RSSFeed.aspx?ModID=1&CID=Sheriffs-Office-7", feedType: "rss", sourceType: "Official", desks: ["crime"], cadence: 10, category: "official" }),
  src("Missoula County Elections", "https://www.missoulacounty.us/government/administration/elections-office", { feedUrl: "https://www.missoulacounty.us/RSSFeed.aspx?ModID=1&CID=Elections-Office-12", feedType: "rss", sourceType: "Official", desks: ["politics"], cadence: 30, category: "official" }),
  src("Montana Secretary of State", "https://sosmt.gov/elections/", { feedUrl: "https://sosmt.gov/elections/news/", feedType: "html", parserKey: "mt-sos", sourceType: "Official", desks: ["politics"], cadence: 60, category: "official" }),
  src("Missoula Area Chamber of Commerce", "https://www.missoulachamber.com/", { feedUrl: "https://www.missoulachamber.com/news/", feedType: "html", parserKey: "chamber", sourceType: "Official", desks: ["business"], cadence: 30, category: "official" }),
  src("Missoula Public Library", "https://www.missoulapubliclibrary.org/", { feedUrl: "https://www.missoulapubliclibrary.org/news/", feedType: "html", parserKey: "library", sourceType: "Official", desks: ["city", "culture"], cadence: 30, category: "official" }),
  src("Zootown Arts Community Center", "https://zootownarts.org/", { feedUrl: "https://zootownarts.org/events/", feedType: "html", parserKey: "zacc", sourceType: "Official", desks: ["culture", "community"], cadence: 60, category: "official" }),
  src("United Way of Missoula County", "https://www.missoulaunitedway.org/", { feedUrl: "https://www.missoulaunitedway.org/news", feedType: "html", parserKey: "united-way", sourceType: "Official", desks: ["community"], cadence: 60, category: "official" }),
  src("Missoula Food Bank", "https://missoulafoodbank.org/", { feedUrl: "https://missoulafoodbank.org/news/", feedType: "html", parserKey: "food-bank", sourceType: "Official", desks: ["community"], cadence: 60, category: "official" }),
  src("YMCA Missoula", "https://www.ymcamissoula.org/", { feedUrl: "https://www.ymcamissoula.org/news", feedType: "html", parserKey: "ymca", sourceType: "Official", desks: ["community", "health", "sports"], cadence: 60, category: "official" }),
  // New Health-desk officials
  src("Missoula City-County Health Department", "https://www.missoulainfo.com/", { feedUrl: "https://www.missoulainfo.com/news", feedType: "html", parserKey: "mc-health", sourceType: "Official", desks: ["health", "city"], cadence: 30, category: "official" }),
  src("Providence St. Patrick Hospital", "https://www.providence.org/locations/mt/st-patrick-hospital", { feedType: "html", parserKey: "providence-stpat", sourceType: "Official", desks: ["health"], cadence: 60, category: "official" }),
  src("Community Medical Center", "https://www.communitymed.org/", { feedType: "html", parserKey: "community-medical", sourceType: "Official", desks: ["health"], cadence: 60, category: "official" }),
  // New Sports-desk official
  src("University of Montana Athletics (Griz)", "https://gogriz.com/", { feedUrl: "https://gogriz.com/composite.xml?print=rss", feedType: "rss", sourceType: "Official", desks: ["sports"], cadence: 15, category: "official" }),

  // ============ CALENDARS ============
  src("Destination Missoula", "https://www.destinationmissoula.org/", { feedUrl: "https://www.destinationmissoula.org/events/", feedType: "html", parserKey: "destination-missoula", sourceType: "Community Calendar", desks: ["culture"], cadence: 15, category: "calendars" }),
  src("Missoula Downtown Partnership", "https://www.missouladowntown.com/", { feedUrl: "https://www.missouladowntown.com/events/", feedType: "html", parserKey: "downtown-partnership", sourceType: "Community Calendar", desks: ["business", "culture"], cadence: 15, category: "calendars" }),
  src("Missoula County Fairgrounds", "https://missoulafairgrounds.com/", { feedUrl: "https://missoulafairgrounds.com/events/", feedType: "html", parserKey: "fairgrounds", sourceType: "Community Calendar", desks: ["culture", "sports"], cadence: 30, category: "calendars" }),
  src("Logjam Presents", "https://logjampresents.com/", { feedUrl: "https://logjampresents.com/events/", feedType: "html", parserKey: "logjam", sourceType: "Community Calendar", desks: ["culture"], cadence: 30, category: "calendars" }),
  src("MissoulaEvents.com", "https://www.missoulaevents.com/", { feedType: "html", feedUrl: "https://www.missoulaevents.com/", parserKey: "missoula-events", sourceType: "Community Calendar", desks: ["culture", "sports", "community"], cadence: 30, category: "calendars" }),
  src("Facebook Events in Missoula", "https://www.facebook.com/events/explore/missoula-mt/108342149195768/", { feedType: "headless", feedUrl: "https://www.facebook.com/events/explore/missoula-mt/108342149195768/", parserKey: "facebook-events-missoula", sourceType: "Community Calendar", desks: ["culture", "community", "sports"], cadence: 60, category: "calendars" }),

  // ============ SOCIAL MEDIA — X / Facebook ============
  // Government & public safety
  src("@MissoulaCounty (X)", "https://x.com/MissoulaCounty", { sourceType: "Social Media", desks: ["city"], cadence: 30, category: "social", handle: "@MissoulaCounty", platform: "x" }),
  src("@mpd_tweet (X)", "https://x.com/mpd_tweet", { sourceType: "Social Media", desks: ["crime", "city"], cadence: 15, category: "social", handle: "@mpd_tweet", platform: "x" }),
  src("@missoulaparks (X)", "https://x.com/missoulaparks", { sourceType: "Social Media", desks: ["city", "community"], cadence: 60, category: "social", handle: "@missoulaparks", platform: "x" }),
  src("@msladowntown (X)", "https://x.com/msladowntown", { sourceType: "Social Media", desks: ["business", "culture"], cadence: 60, category: "social", handle: "@msladowntown", platform: "x" }),
  src("@mslainmotion (X)", "https://x.com/mslainmotion", { sourceType: "Social Media", desks: ["city"], cadence: 60, category: "social", handle: "@mslainmotion", platform: "x" }),
  // Events & tourism
  src("@visitmissoula (X)", "https://x.com/visitmissoula", { sourceType: "Social Media", desks: ["culture"], cadence: 60, category: "social", handle: "@visitmissoula", platform: "x" }),
  src("@GatherBoard (X)", "https://x.com/GatherBoard", { sourceType: "Social Media", desks: ["culture", "sports"], cadence: 60, category: "social", handle: "@GatherBoard", platform: "x" }),
  // Weather
  src("@NWSMissoula (X)", "https://x.com/NWSMissoula", { sourceType: "Social Media", desks: ["city", "health"], cadence: 15, category: "social", handle: "@NWSMissoula", platform: "x" }),
  // UM & Grizzlies
  src("@umontana (X)", "https://x.com/umontana", { sourceType: "Social Media", desks: ["city", "sports"], cadence: 60, category: "social", handle: "@umontana", platform: "x" }),
  src("@UMGRIZZLIES (X)", "https://x.com/UMGRIZZLIES", { sourceType: "Social Media", desks: ["sports"], cadence: 30, category: "social", handle: "@UMGRIZZLIES", platform: "x" }),
  src("@MontanaGrizFB (X)", "https://x.com/MontanaGrizFB", { sourceType: "Social Media", desks: ["sports"], cadence: 30, category: "social", handle: "@MontanaGrizFB", platform: "x" }),
  src("@MontanaGrizBB (X)", "https://x.com/MontanaGrizBB", { sourceType: "Social Media", desks: ["sports"], cadence: 30, category: "social", handle: "@MontanaGrizBB", platform: "x" }),
  // Statewide newsrooms (X)
  src("@kpaxnews (X)", "https://x.com/kpaxnews", { sourceType: "Social Media", desks: ["city", "crime", "culture"], cadence: 30, category: "social", handle: "@kpaxnews", platform: "x" }),
  src("@missoulian (X)", "https://x.com/missoulian", { sourceType: "Social Media", desks: ["city", "crime", "culture"], cadence: 30, category: "social", handle: "@missoulian", platform: "x" }),
  src("@Missoula_Indy (X)", "https://x.com/Missoula_Indy", { sourceType: "Social Media", desks: ["culture", "politics"], cadence: 60, category: "social", handle: "@Missoula_Indy", platform: "x" }),
  src("@mtfreepress (X)", "https://x.com/mtfreepress", { sourceType: "Social Media", desks: ["politics", "health"], cadence: 60, category: "social", handle: "@mtfreepress", platform: "x" }),
  src("@mtpublicradio (X)", "https://x.com/mtpublicradio", { sourceType: "Social Media", desks: ["city", "culture", "politics"], cadence: 60, category: "social", handle: "@mtpublicradio", platform: "x" }),
  src("@KXLF (X)", "https://x.com/KXLF", { sourceType: "Social Media", desks: ["city", "crime"], cadence: 60, category: "social", handle: "@KXLF", platform: "x" }),
  src("@NBCMontana (X)", "https://x.com/NBCMontana", { sourceType: "Social Media", desks: ["city", "crime"], cadence: 60, category: "social", handle: "@NBCMontana", platform: "x" }),
  src("@bozchron (X)", "https://x.com/bozchron", { sourceType: "Social Media", desks: ["city"], cadence: 60, category: "social", handle: "@bozchron", platform: "x" }),
  src("@KTVQ (X)", "https://x.com/KTVQ", { sourceType: "Social Media", desks: ["city", "crime"], cadence: 60, category: "social", handle: "@KTVQ", platform: "x" }),
  src("@KBZK (X)", "https://x.com/KBZK", { sourceType: "Social Media", desks: ["city"], cadence: 60, category: "social", handle: "@KBZK", platform: "x" }),
  src("@billingsgazette (X)", "https://x.com/billingsgazette", { sourceType: "Social Media", desks: ["city"], cadence: 60, category: "social", handle: "@billingsgazette", platform: "x" }),
  src("@montananews (X)", "https://x.com/montananews", { sourceType: "Social Media", desks: ["city", "crime"], cadence: 60, category: "social", handle: "@montananews", platform: "x" }),
  src("@KeilaSzpaller (X)", "https://x.com/KeilaSzpaller", { sourceType: "Social Media", desks: ["city", "politics"], cadence: 60, category: "social", handle: "@KeilaSzpaller", platform: "x" }),
  src("@FlatheadBeacon (X)", "https://x.com/FlatheadBeacon", { sourceType: "Social Media", desks: ["city"], cadence: 60, category: "social", handle: "@FlatheadBeacon", platform: "x" }),
  src("@MontanaStandard (X)", "https://x.com/MontanaStandard", { sourceType: "Social Media", desks: ["city"], cadence: 60, category: "social", handle: "@MontanaStandard", platform: "x" }),
  src("@KRTV (X)", "https://x.com/KRTV", { sourceType: "Social Media", desks: ["city", "crime"], cadence: 60, category: "social", handle: "@KRTV", platform: "x" }),
  src("@helenaironline (X)", "https://x.com/helenaironline", { sourceType: "Social Media", desks: ["politics"], cadence: 60, category: "social", handle: "@helenaironline", platform: "x" }),
  // Elected officials — their words, neutrally aggregated
  src("@SteveDaines (X) · U.S. Senator", "https://x.com/SteveDaines", { sourceType: "Social Media", desks: ["politics"], cadence: 60, category: "social", handle: "@SteveDaines", platform: "x" }),
  src("Office of Governor Greg Gianforte (X)", "https://x.com/GovGianforte", { sourceType: "Social Media", desks: ["politics"], cadence: 60, category: "social", handle: "@GovGianforte", platform: "x" }),
  src("Mayor of Missoula (X)", "https://x.com/missoulamayor", { sourceType: "Social Media", desks: ["politics", "city"], cadence: 60, category: "social", handle: "@missoulamayor", platform: "x" }),
];
